// import { fab } from '@fortawesome/free-brands-svg-icons';
import {
    faAddressBook as solid_AddressBook,
    faAddressCard as solid_AddressCard,
    faAdjust as solid_Adjust,
    faAlignCenter as solid_AlignCenter,
    faAlignJustify as solid_AlignJustify,
    faAlignLeft as solid_AlignLeft,
    faAlignRight as solid_AlignRight,
    faAllergies as solid_Allergies,
    faAmbulance as solid_Ambulance,
    faAmericanSignLanguageInterpreting as solid_AmericanSignLanguageInterpreting,
    faAnchor as solid_Anchor,
    faAngleDoubleDown as solid_AngleDoubleDown,
    faAngleDoubleLeft as solid_AngleDoubleLeft,
    faAngleDoubleRight as solid_AngleDoubleRight,
    faAngleDoubleUp as solid_AngleDoubleUp,
    faAngleDown as solid_AngleDown,
    faAngleLeft as solid_AngleLeft,
    faAngleRight as solid_AngleRight,
    faAngleUp as solid_AngleUp,
    faArchive as solid_Archive,
    faArrowAltCircleDown as solid_ArrowAltCircleDown,
    faArrowAltCircleLeft as solid_ArrowAltCircleLeft,
    faArrowAltCircleRight as solid_ArrowAltCircleRight,
    faArrowAltCircleUp as solid_ArrowAltCircleUp,
    faArrowCircleDown as solid_ArrowCircleDown,
    faArrowCircleLeft as solid_ArrowCircleLeft,
    faArrowCircleRight as solid_ArrowCircleRight,
    faArrowCircleUp as solid_ArrowCircleUp,
    faArrowDown as solid_ArrowDown,
    faArrowLeft as solid_ArrowLeft,
    faArrowRight as solid_ArrowRight,
    faArrowUp as solid_ArrowUp,
    faArrowsAlt as solid_ArrowsAlt,
    faArrowsAltH as solid_ArrowsAltH,
    faArrowsAltV as solid_ArrowsAltV,
    faAssistiveListeningSystems as solid_AssistiveListeningSystems,
    faAsterisk as solid_Asterisk,
    faAt as solid_At,
    faAudioDescription as solid_AudioDescription,
    faBackward as solid_Backward,
    faBalanceScale as solid_BalanceScale,
    faBan as solid_Ban,
    faBandAid as solid_BandAid,
    faBarcode as solid_Barcode,
    faBars as solid_Bars,
    faBaseballBall as solid_BaseballBall,
    faBasketballBall as solid_BasketballBall,
    faBath as solid_Bath,
    faBatteryEmpty as solid_BatteryEmpty,
    faBatteryFull as solid_BatteryFull,
    faBatteryHalf as solid_BatteryHalf,
    faBatteryQuarter as solid_BatteryQuarter,
    faBatteryThreeQuarters as solid_BatteryThreeQuarters,
    faBed as solid_Bed,
    faBeer as solid_Beer,
    faBell as solid_Bell,
    faBellSlash as solid_BellSlash,
    faBicycle as solid_Bicycle,
    faBinoculars as solid_Binoculars,
    faBirthdayCake as solid_BirthdayCake,
    faBlender as solid_Blender,
    faBlind as solid_Blind,
    faBold as solid_Bold,
    faBolt as solid_Bolt,
    faBomb as solid_Bomb,
    faBook as solid_Book,
    faBookOpen as solid_BookOpen,
    faBookmark as solid_Bookmark,
    faBowlingBall as solid_BowlingBall,
    faBox as solid_Box,
    faBoxOpen as solid_BoxOpen,
    faBoxes as solid_Boxes,
    faBraille as solid_Braille,
    faBriefcase as solid_Briefcase,
    faBriefcaseMedical as solid_BriefcaseMedical,
    faBroadcastTower as solid_BroadcastTower,
    faBroom as solid_Broom,
    faBug as solid_Bug,
    faBuilding as solid_Building,
    faBullhorn as solid_Bullhorn,
    faBullseye as solid_Bullseye,
    faBurn as solid_Burn,
    faBus as solid_Bus,
    faCalculator as solid_Calculator,
    faCalendar as solid_Calendar,
    faCalendarAlt as solid_CalendarAlt,
    faCalendarCheck as solid_CalendarCheck,
    faCalendarMinus as solid_CalendarMinus,
    faCalendarPlus as solid_CalendarPlus,
    faCalendarTimes as solid_CalendarTimes,
    faCamera as solid_Camera,
    faCameraRetro as solid_CameraRetro,
    faCapsules as solid_Capsules,
    faCar as solid_Car,
    faCaretDown as solid_CaretDown,
    faCaretLeft as solid_CaretLeft,
    faCaretRight as solid_CaretRight,
    faCaretSquareDown as solid_CaretSquareDown,
    faCaretSquareLeft as solid_CaretSquareLeft,
    faCaretSquareRight as solid_CaretSquareRight,
    faCaretSquareUp as solid_CaretSquareUp,
    faCaretUp as solid_CaretUp,
    faCartArrowDown as solid_CartArrowDown,
    faCartPlus as solid_CartPlus,
    faCertificate as solid_Certificate,
    faChalkboard as solid_Chalkboard,
    faChalkboardTeacher as solid_ChalkboardTeacher,
    faChartArea as solid_ChartArea,
    faChartBar as solid_ChartBar,
    faChartLine as solid_ChartLine,
    faChartPie as solid_ChartPie,
    faCheck as solid_Check,
    faCheckCircle as solid_CheckCircle,
    faCheckSquare as solid_CheckSquare,
    faChess as solid_Chess,
    faChessBishop as solid_ChessBishop,
    faChessBoard as solid_ChessBoard,
    faChessKing as solid_ChessKing,
    faChessKnight as solid_ChessKnight,
    faChessPawn as solid_ChessPawn,
    faChessQueen as solid_ChessQueen,
    faChessRook as solid_ChessRook,
    faChevronCircleDown as solid_ChevronCircleDown,
    faChevronCircleLeft as solid_ChevronCircleLeft,
    faChevronCircleRight as solid_ChevronCircleRight,
    faChevronCircleUp as solid_ChevronCircleUp,
    faChevronDown as solid_ChevronDown,
    faChevronLeft as solid_ChevronLeft,
    faChevronRight as solid_ChevronRight,
    faChevronUp as solid_ChevronUp,
    faChild as solid_Child,
    faChurch as solid_Church,
    faCircle as solid_Circle,
    faCircleNotch as solid_CircleNotch,
    faClipboard as solid_Clipboard,
    faClipboardCheck as solid_ClipboardCheck,
    faClipboardList as solid_ClipboardList,
    faClock as solid_Clock,
    faClone as solid_Clone,
    faClosedCaptioning as solid_ClosedCaptioning,
    faCloud as solid_Cloud,
    faCloudDownloadAlt as solid_CloudDownloadAlt,
    faCloudUploadAlt as solid_CloudUploadAlt,
    faCode as solid_Code,
    faCodeBranch as solid_CodeBranch,
    faCoffee as solid_Coffee,
    faCog as solid_Cog,
    faCogs as solid_Cogs,
    faCoins as solid_Coins,
    faColumns as solid_Columns,
    faComment as solid_Comment,
    faCommentAlt as solid_CommentAlt,
    faCommentDots as solid_CommentDots,
    faCommentSlash as solid_CommentSlash,
    faComments as solid_Comments,
    faCompactDisc as solid_CompactDisc,
    faCompass as solid_Compass,
    faCompress as solid_Compress,
    faCopy as solid_Copy,
    faCopyright as solid_Copyright,
    faCouch as solid_Couch,
    faCreditCard as solid_CreditCard,
    faCrop as solid_Crop,
    faCrosshairs as solid_Crosshairs,
    faCrow as solid_Crow,
    faCrown as solid_Crown,
    faCube as solid_Cube,
    faCubes as solid_Cubes,
    faCut as solid_Cut,
    faDatabase as solid_Database,
    faDeaf as solid_Deaf,
    faDesktop as solid_Desktop,
    faDiagnoses as solid_Diagnoses,
    faDice as solid_Dice,
    faDiceFive as solid_DiceFive,
    faDiceFour as solid_DiceFour,
    faDiceOne as solid_DiceOne,
    faDiceSix as solid_DiceSix,
    faDiceThree as solid_DiceThree,
    faDiceTwo as solid_DiceTwo,
    faDivide as solid_Divide,
    faDna as solid_Dna,
    faDollarSign as solid_DollarSign,
    faDolly as solid_Dolly,
    faDollyFlatbed as solid_DollyFlatbed,
    faDonate as solid_Donate,
    faDoorClosed as solid_DoorClosed,
    faDoorOpen as solid_DoorOpen,
    faDotCircle as solid_DotCircle,
    faDove as solid_Dove,
    faDownload as solid_Download,
    faDumbbell as solid_Dumbbell,
    faEdit as solid_Edit,
    faEject as solid_Eject,
    faEllipsisH as solid_EllipsisH,
    faEllipsisV as solid_EllipsisV,
    faEnvelope as solid_Envelope,
    faEnvelopeOpen as solid_EnvelopeOpen,
    faEnvelopeSquare as solid_EnvelopeSquare,
    faEquals as solid_Equals,
    faEraser as solid_Eraser,
    faEuroSign as solid_EuroSign,
    faExchangeAlt as solid_ExchangeAlt,
    faExclamation as solid_Exclamation,
    faExclamationCircle as solid_ExclamationCircle,
    faExclamationTriangle as solid_ExclamationTriangle,
    faExpand as solid_Expand,
    faExpandArrowsAlt as solid_ExpandArrowsAlt,
    faExternalLinkAlt as solid_ExternalLinkAlt,
    faExternalLinkSquareAlt as solid_ExternalLinkSquareAlt,
    faEye as solid_Eye,
    faEyeDropper as solid_EyeDropper,
    faEyeSlash as solid_EyeSlash,
    faFastBackward as solid_FastBackward,
    faFastForward as solid_FastForward,
    faFax as solid_Fax,
    faFeather as solid_Feather,
    faFemale as solid_Female,
    faFighterJet as solid_FighterJet,
    faFile as solid_File,
    faFileAlt as solid_FileAlt,
    faFileArchive as solid_FileArchive,
    faFileAudio as solid_FileAudio,
    faFileCode as solid_FileCode,
    faFileExcel as solid_FileExcel,
    faFileImage as solid_FileImage,
    faFileMedical as solid_FileMedical,
    faFileMedicalAlt as solid_FileMedicalAlt,
    faFilePdf as solid_FilePdf,
    faFilePowerpoint as solid_FilePowerpoint,
    faFileVideo as solid_FileVideo,
    faFileWord as solid_FileWord,
    faFilm as solid_Film,
    faFilter as solid_Filter,
    faFire as solid_Fire,
    faFireExtinguisher as solid_FireExtinguisher,
    faFirstAid as solid_FirstAid,
    faFlag as solid_Flag,
    faFlagCheckered as solid_FlagCheckered,
    faFlask as solid_Flask,
    faFolder as solid_Folder,
    faFolderOpen as solid_FolderOpen,
    faFont as solid_Font,
    faFontAwesomeLogoFull as solid_FontAwesomeLogoFull,
    faFootballBall as solid_FootballBall,
    faForward as solid_Forward,
    faFrog as solid_Frog,
    faFrown as solid_Frown,
    faFutbol as solid_Futbol,
    faGamepad as solid_Gamepad,
    faGasPump as solid_GasPump,
    faGavel as solid_Gavel,
    faGem as solid_Gem,
    faGenderless as solid_Genderless,
    faGift as solid_Gift,
    faGlassMartini as solid_GlassMartini,
    faGlasses as solid_Glasses,
    faGlobe as solid_Globe,
    faGolfBall as solid_GolfBall,
    faGraduationCap as solid_GraduationCap,
    faGreaterThan as solid_GreaterThan,
    faGreaterThanEqual as solid_GreaterThanEqual,
    faHSquare as solid_HSquare,
    faHandHolding as solid_HandHolding,
    faHandHoldingHeart as solid_HandHoldingHeart,
    faHandHoldingUsd as solid_HandHoldingUsd,
    faHandLizard as solid_HandLizard,
    faHandPaper as solid_HandPaper,
    faHandPeace as solid_HandPeace,
    faHandPointDown as solid_HandPointDown,
    faHandPointLeft as solid_HandPointLeft,
    faHandPointRight as solid_HandPointRight,
    faHandPointUp as solid_HandPointUp,
    faHandPointer as solid_HandPointer,
    faHandRock as solid_HandRock,
    faHandScissors as solid_HandScissors,
    faHandSpock as solid_HandSpock,
    faHands as solid_Hands,
    faHandsHelping as solid_HandsHelping,
    faHandshake as solid_Handshake,
    faHashtag as solid_Hashtag,
    faHdd as solid_Hdd,
    faHeading as solid_Heading,
    faHeadphones as solid_Headphones,
    faHeart as solid_Heart,
    faHeartbeat as solid_Heartbeat,
    faHelicopter as solid_Helicopter,
    faHistory as solid_History,
    faHockeyPuck as solid_HockeyPuck,
    faHome as solid_Home,
    faHospital as solid_Hospital,
    faHospitalAlt as solid_HospitalAlt,
    faHospitalSymbol as solid_HospitalSymbol,
    faHourglass as solid_Hourglass,
    faHourglassEnd as solid_HourglassEnd,
    faHourglassHalf as solid_HourglassHalf,
    faHourglassStart as solid_HourglassStart,
    faICursor as solid_ICursor,
    faIdBadge as solid_IdBadge,
    faIdCard as solid_IdCard,
    faIdCardAlt as solid_IdCardAlt,
    faImage as solid_Image,
    faImages as solid_Images,
    faInbox as solid_Inbox,
    faIndent as solid_Indent,
    faIndustry as solid_Industry,
    faInfinity as solid_Infinity,
    faInfo as solid_Info,
    faInfoCircle as solid_InfoCircle,
    faItalic as solid_Italic,
    faKey as solid_Key,
    faKeyboard as solid_Keyboard,
    faKiwiBird as solid_KiwiBird,
    faLanguage as solid_Language,
    faLaptop as solid_Laptop,
    faLeaf as solid_Leaf,
    faLemon as solid_Lemon,
    faLessThan as solid_LessThan,
    faLessThanEqual as solid_LessThanEqual,
    faLevelDownAlt as solid_LevelDownAlt,
    faLevelUpAlt as solid_LevelUpAlt,
    faLifeRing as solid_LifeRing,
    faLightbulb as solid_Lightbulb,
    faLink as solid_Link,
    faLiraSign as solid_LiraSign,
    faList as solid_List,
    faListAlt as solid_ListAlt,
    faListOl as solid_ListOl,
    faListUl as solid_ListUl,
    faLocationArrow as solid_LocationArrow,
    faLock as solid_Lock,
    faLockOpen as solid_LockOpen,
    faLongArrowAltDown as solid_LongArrowAltDown,
    faLongArrowAltLeft as solid_LongArrowAltLeft,
    faLongArrowAltRight as solid_LongArrowAltRight,
    faLongArrowAltUp as solid_LongArrowAltUp,
    faLowVision as solid_LowVision,
    faMagic as solid_Magic,
    faMagnet as solid_Magnet,
    faMale as solid_Male,
    faMap as solid_Map,
    faMapMarker as solid_MapMarker,
    faMapMarkerAlt as solid_MapMarkerAlt,
    faMapPin as solid_MapPin,
    faMapSigns as solid_MapSigns,
    faMars as solid_Mars,
    faMarsDouble as solid_MarsDouble,
    faMarsStroke as solid_MarsStroke,
    faMarsStrokeH as solid_MarsStrokeH,
    faMarsStrokeV as solid_MarsStrokeV,
    faMedkit as solid_Medkit,
    faMeh as solid_Meh,
    faMemory as solid_Memory,
    faMercury as solid_Mercury,
    faMicrochip as solid_Microchip,
    faMicrophone as solid_Microphone,
    faMicrophoneAlt as solid_MicrophoneAlt,
    faMicrophoneAltSlash as solid_MicrophoneAltSlash,
    faMicrophoneSlash as solid_MicrophoneSlash,
    faMinus as solid_Minus,
    faMinusCircle as solid_MinusCircle,
    faMinusSquare as solid_MinusSquare,
    faMobile as solid_Mobile,
    faMobileAlt as solid_MobileAlt,
    faMoneyBill as solid_MoneyBill,
    faMoneyBillAlt as solid_MoneyBillAlt,
    faMoneyBillWave as solid_MoneyBillWave,
    faMoneyBillWaveAlt as solid_MoneyBillWaveAlt,
    faMoneyCheck as solid_MoneyCheck,
    faMoneyCheckAlt as solid_MoneyCheckAlt,
    faMoon as solid_Moon,
    faMotorcycle as solid_Motorcycle,
    faMousePointer as solid_MousePointer,
    faMusic as solid_Music,
    faNeuter as solid_Neuter,
    faNewspaper as solid_Newspaper,
    faNotEqual as solid_NotEqual,
    faNotesMedical as solid_NotesMedical,
    faObjectGroup as solid_ObjectGroup,
    faObjectUngroup as solid_ObjectUngroup,
    faOutdent as solid_Outdent,
    faPaintBrush as solid_PaintBrush,
    faPalette as solid_Palette,
    faPallet as solid_Pallet,
    faPaperPlane as solid_PaperPlane,
    faPaperclip as solid_Paperclip,
    faParachuteBox as solid_ParachuteBox,
    faParagraph as solid_Paragraph,
    faParking as solid_Parking,
    faPaste as solid_Paste,
    faPause as solid_Pause,
    faPauseCircle as solid_PauseCircle,
    faPaw as solid_Paw,
    faPenSquare as solid_PenSquare,
    faPencilAlt as solid_PencilAlt,
    faPeopleCarry as solid_PeopleCarry,
    faPercent as solid_Percent,
    faPercentage as solid_Percentage,
    faPhone as solid_Phone,
    faPhoneSlash as solid_PhoneSlash,
    faPhoneSquare as solid_PhoneSquare,
    faPhoneVolume as solid_PhoneVolume,
    faPiggyBank as solid_PiggyBank,
    faPills as solid_Pills,
    faPlane as solid_Plane,
    faPlay as solid_Play,
    faPlayCircle as solid_PlayCircle,
    faPlug as solid_Plug,
    faPlus as solid_Plus,
    faPlusCircle as solid_PlusCircle,
    faPlusSquare as solid_PlusSquare,
    faPodcast as solid_Podcast,
    faPoo as solid_Poo,
    faPortrait as solid_Portrait,
    faPoundSign as solid_PoundSign,
    faPowerOff as solid_PowerOff,
    faPrescriptionBottle as solid_PrescriptionBottle,
    faPrescriptionBottleAlt as solid_PrescriptionBottleAlt,
    faPrint as solid_Print,
    faProcedures as solid_Procedures,
    faProjectDiagram as solid_ProjectDiagram,
    faPuzzlePiece as solid_PuzzlePiece,
    faQrcode as solid_Qrcode,
    faQuestion as solid_Question,
    faQuestionCircle as solid_QuestionCircle,
    faQuidditch as solid_Quidditch,
    faQuoteLeft as solid_QuoteLeft,
    faQuoteRight as solid_QuoteRight,
    faRandom as solid_Random,
    faReceipt as solid_Receipt,
    faRecycle as solid_Recycle,
    faRedo as solid_Redo,
    faRedoAlt as solid_RedoAlt,
    faRegistered as solid_Registered,
    faReply as solid_Reply,
    faReplyAll as solid_ReplyAll,
    faRetweet as solid_Retweet,
    faRibbon as solid_Ribbon,
    faRoad as solid_Road,
    faRobot as solid_Robot,
    faRocket as solid_Rocket,
    faRss as solid_Rss,
    faRssSquare as solid_RssSquare,
    faRubleSign as solid_RubleSign,
    faRuler as solid_Ruler,
    faRulerCombined as solid_RulerCombined,
    faRulerHorizontal as solid_RulerHorizontal,
    faRulerVertical as solid_RulerVertical,
    faRupeeSign as solid_RupeeSign,
    faSave as solid_Save,
    faSchool as solid_School,
    faScrewdriver as solid_Screwdriver,
    faSearch as solid_Search,
    faSearchMinus as solid_SearchMinus,
    faSearchPlus as solid_SearchPlus,
    faSeedling as solid_Seedling,
    faServer as solid_Server,
    faShare as solid_Share,
    faShareAlt as solid_ShareAlt,
    faShareAltSquare as solid_ShareAltSquare,
    faShareSquare as solid_ShareSquare,
    faShekelSign as solid_ShekelSign,
    faShieldAlt as solid_ShieldAlt,
    faShip as solid_Ship,
    faShippingFast as solid_ShippingFast,
    faShoePrints as solid_ShoePrints,
    faShoppingBag as solid_ShoppingBag,
    faShoppingBasket as solid_ShoppingBasket,
    faShoppingCart as solid_ShoppingCart,
    faShower as solid_Shower,
    faSign as solid_Sign,
    faSignInAlt as solid_SignInAlt,
    faSignLanguage as solid_SignLanguage,
    faSignOutAlt as solid_SignOutAlt,
    faSignal as solid_Signal,
    faSitemap as solid_Sitemap,
    faSkull as solid_Skull,
    faSlidersH as solid_SlidersH,
    faSmile as solid_Smile,
    faSmoking as solid_Smoking,
    faSmokingBan as solid_SmokingBan,
    faSnowflake as solid_Snowflake,
    faSort as solid_Sort,
    faSortAlphaDown as solid_SortAlphaDown,
    faSortAlphaUp as solid_SortAlphaUp,
    faSortAmountDown as solid_SortAmountDown,
    faSortAmountUp as solid_SortAmountUp,
    faSortDown as solid_SortDown,
    faSortNumericDown as solid_SortNumericDown,
    faSortNumericUp as solid_SortNumericUp,
    faSortUp as solid_SortUp,
    faSpaceShuttle as solid_SpaceShuttle,
    faSpinner as solid_Spinner,
    faSquare as solid_Square,
    faSquareFull as solid_SquareFull,
    faStar as solid_Star,
    faStarHalf as solid_StarHalf,
    faStepBackward as solid_StepBackward,
    faStepForward as solid_StepForward,
    faStethoscope as solid_Stethoscope,
    faStickyNote as solid_StickyNote,
    faStop as solid_Stop,
    faStopCircle as solid_StopCircle,
    faStopwatch as solid_Stopwatch,
    faStore as solid_Store,
    faStoreAlt as solid_StoreAlt,
    faStream as solid_Stream,
    faStreetView as solid_StreetView,
    faStrikethrough as solid_Strikethrough,
    faStroopwafel as solid_Stroopwafel,
    faSubscript as solid_Subscript,
    faSubway as solid_Subway,
    faSuitcase as solid_Suitcase,
    faSun as solid_Sun,
    faSuperscript as solid_Superscript,
    faSync as solid_Sync,
    faSyncAlt as solid_SyncAlt,
    faSyringe as solid_Syringe,
    faTable as solid_Table,
    faTableTennis as solid_TableTennis,
    faTablet as solid_Tablet,
    faTabletAlt as solid_TabletAlt,
    faTablets as solid_Tablets,
    faTachometerAlt as solid_TachometerAlt,
    faTag as solid_Tag,
    faTags as solid_Tags,
    faTape as solid_Tape,
    faTasks as solid_Tasks,
    faTaxi as solid_Taxi,
    faTerminal as solid_Terminal,
    faTextHeight as solid_TextHeight,
    faTextWidth as solid_TextWidth,
    faTh as solid_Th,
    faThLarge as solid_ThLarge,
    faThList as solid_ThList,
    faThermometer as solid_Thermometer,
    faThermometerEmpty as solid_ThermometerEmpty,
    faThermometerFull as solid_ThermometerFull,
    faThermometerHalf as solid_ThermometerHalf,
    faThermometerQuarter as solid_ThermometerQuarter,
    faThermometerThreeQuarters as solid_ThermometerThreeQuarters,
    faThumbsDown as solid_ThumbsDown,
    faThumbsUp as solid_ThumbsUp,
    faThumbtack as solid_Thumbtack,
    faTicketAlt as solid_TicketAlt,
    faTimes as solid_Times,
    faTimesCircle as solid_TimesCircle,
    faTint as solid_Tint,
    faToggleOff as solid_ToggleOff,
    faToggleOn as solid_ToggleOn,
    faToolbox as solid_Toolbox,
    faTrademark as solid_Trademark,
    faTrain as solid_Train,
    faTransgender as solid_Transgender,
    faTransgenderAlt as solid_TransgenderAlt,
    faTrash as solid_Trash,
    faTrashAlt as solid_TrashAlt,
    faTree as solid_Tree,
    faTrophy as solid_Trophy,
    faTruck as solid_Truck,
    faTruckLoading as solid_TruckLoading,
    faTruckMoving as solid_TruckMoving,
    faTshirt as solid_Tshirt,
    faTty as solid_Tty,
    faTv as solid_Tv,
    faUmbrella as solid_Umbrella,
    faUnderline as solid_Underline,
    faUndo as solid_Undo,
    faUndoAlt as solid_UndoAlt,
    faUniversalAccess as solid_UniversalAccess,
    faUniversity as solid_University,
    faUnlink as solid_Unlink,
    faUnlock as solid_Unlock,
    faUnlockAlt as solid_UnlockAlt,
    faUpload as solid_Upload,
    faUser as solid_User,
    faUserAlt as solid_UserAlt,
    faUserAltSlash as solid_UserAltSlash,
    faUserAstronaut as solid_UserAstronaut,
    faUserCheck as solid_UserCheck,
    faUserCircle as solid_UserCircle,
    faUserClock as solid_UserClock,
    faUserCog as solid_UserCog,
    faUserEdit as solid_UserEdit,
    faUserFriends as solid_UserFriends,
    faUserGraduate as solid_UserGraduate,
    faUserLock as solid_UserLock,
    faUserMd as solid_UserMd,
    faUserMinus as solid_UserMinus,
    faUserNinja as solid_UserNinja,
    faUserPlus as solid_UserPlus,
    faUserSecret as solid_UserSecret,
    faUserShield as solid_UserShield,
    faUserSlash as solid_UserSlash,
    faUserTag as solid_UserTag,
    faUserTie as solid_UserTie,
    faUserTimes as solid_UserTimes,
    faUsers as solid_Users,
    faUsersCog as solid_UsersCog,
    faUtensilSpoon as solid_UtensilSpoon,
    faUtensils as solid_Utensils,
    faVenus as solid_Venus,
    faVenusDouble as solid_VenusDouble,
    faVenusMars as solid_VenusMars,
    faVial as solid_Vial,
    faVials as solid_Vials,
    faVideo as solid_Video,
    faVideoSlash as solid_VideoSlash,
    faVolleyballBall as solid_VolleyballBall,
    faVolumeDown as solid_VolumeDown,
    faVolumeOff as solid_VolumeOff,
    faVolumeUp as solid_VolumeUp,
    faWalking as solid_Walking,
    faWallet as solid_Wallet,
    faWarehouse as solid_Warehouse,
    faWeight as solid_Weight,
    faWheelchair as solid_Wheelchair,
    faWifi as solid_Wifi,
    faWindowClose as solid_WindowClose,
    faWindowMaximize as solid_WindowMaximize,
    faWindowMinimize as solid_WindowMinimize,
    faWindowRestore as solid_WindowRestore,
    faWineGlass as solid_WineGlass,
    faWonSign as solid_WonSign,
    faWrench as solid_Wrench,
    faXRay as solid_XRay,
    faYenSign as solid_YenSign,
} from '@fortawesome/free-solid-svg-icons';
import {
    faAddressBook as regular_AddressBook,
    faAddressCard as regular_AddressCard,
    faArrowAltCircleDown as regular_ArrowAltCircleDown,
    faArrowAltCircleLeft as regular_ArrowAltCircleLeft,
    faArrowAltCircleRight as regular_ArrowAltCircleRight,
    faArrowAltCircleUp as regular_ArrowAltCircleUp,
    faBell as regular_Bell,
    faBellSlash as regular_BellSlash,
    faBookmark as regular_Bookmark,
    faBuilding as regular_Building,
    faCalendar as regular_Calendar,
    faCalendarAlt as regular_CalendarAlt,
    faCalendarCheck as regular_CalendarCheck,
    faCalendarMinus as regular_CalendarMinus,
    faCalendarPlus as regular_CalendarPlus,
    faCalendarTimes as regular_CalendarTimes,
    faCaretSquareDown as regular_CaretSquareDown,
    faCaretSquareLeft as regular_CaretSquareLeft,
    faCaretSquareRight as regular_CaretSquareRight,
    faCaretSquareUp as regular_CaretSquareUp,
    faChartBar as regular_ChartBar,
    faCheckCircle as regular_CheckCircle,
    faCheckSquare as regular_CheckSquare,
    faCircle as regular_Circle,
    faClipboard as regular_Clipboard,
    faClock as regular_Clock,
    faClone as regular_Clone,
    faClosedCaptioning as regular_ClosedCaptioning,
    faComment as regular_Comment,
    faCommentAlt as regular_CommentAlt,
    faCommentDots as regular_CommentDots,
    faComments as regular_Comments,
    faCompass as regular_Compass,
    faCopy as regular_Copy,
    faCopyright as regular_Copyright,
    faCreditCard as regular_CreditCard,
    faDotCircle as regular_DotCircle,
    faEdit as regular_Edit,
    faEnvelope as regular_Envelope,
    faEnvelopeOpen as regular_EnvelopeOpen,
    faEye as regular_Eye,
    faEyeSlash as regular_EyeSlash,
    faFile as regular_File,
    faFileAlt as regular_FileAlt,
    faFileArchive as regular_FileArchive,
    faFileAudio as regular_FileAudio,
    faFileCode as regular_FileCode,
    faFileExcel as regular_FileExcel,
    faFileImage as regular_FileImage,
    faFilePdf as regular_FilePdf,
    faFilePowerpoint as regular_FilePowerpoint,
    faFileVideo as regular_FileVideo,
    faFileWord as regular_FileWord,
    faFlag as regular_Flag,
    faFolder as regular_Folder,
    faFolderOpen as regular_FolderOpen,
    faFontAwesomeLogoFull as regular_FontAwesomeLogoFull,
    faFrown as regular_Frown,
    faFutbol as regular_Futbol,
    faGem as regular_Gem,
    faHandLizard as regular_HandLizard,
    faHandPaper as regular_HandPaper,
    faHandPeace as regular_HandPeace,
    faHandPointDown as regular_HandPointDown,
    faHandPointLeft as regular_HandPointLeft,
    faHandPointRight as regular_HandPointRight,
    faHandPointUp as regular_HandPointUp,
    faHandPointer as regular_HandPointer,
    faHandRock as regular_HandRock,
    faHandScissors as regular_HandScissors,
    faHandSpock as regular_HandSpock,
    faHandshake as regular_Handshake,
    faHdd as regular_Hdd,
    faHeart as regular_Heart,
    faHospital as regular_Hospital,
    faHourglass as regular_Hourglass,
    faIdBadge as regular_IdBadge,
    faIdCard as regular_IdCard,
    faImage as regular_Image,
    faImages as regular_Images,
    faKeyboard as regular_Keyboard,
    faLemon as regular_Lemon,
    faLifeRing as regular_LifeRing,
    faLightbulb as regular_Lightbulb,
    faListAlt as regular_ListAlt,
    faMap as regular_Map,
    faMeh as regular_Meh,
    faMinusSquare as regular_MinusSquare,
    faMoneyBillAlt as regular_MoneyBillAlt,
    faMoon as regular_Moon,
    faNewspaper as regular_Newspaper,
    faObjectGroup as regular_ObjectGroup,
    faObjectUngroup as regular_ObjectUngroup,
    faPaperPlane as regular_PaperPlane,
    faPauseCircle as regular_PauseCircle,
    faPlayCircle as regular_PlayCircle,
    faPlusSquare as regular_PlusSquare,
    faQuestionCircle as regular_QuestionCircle,
    faRegistered as regular_Registered,
    faSave as regular_Save,
    faShareSquare as regular_ShareSquare,
    faSmile as regular_Smile,
    faSnowflake as regular_Snowflake,
    faSquare as regular_Square,
    faStar as regular_Star,
    faStarHalf as regular_StarHalf,
    faStickyNote as regular_StickyNote,
    faStopCircle as regular_StopCircle,
    faSun as regular_Sun,
    faThumbsDown as regular_ThumbsDown,
    faThumbsUp as regular_ThumbsUp,
    faTimesCircle as regular_TimesCircle,
    faTrashAlt as regular_TrashAlt,
    faUser as regular_User,
    faUserCircle as regular_UserCircle,
    faWindowClose as regular_WindowClose,
    faWindowMaximize as regular_WindowMaximize,
    faWindowMinimize as regular_WindowMinimize,
    faWindowRestore as regular_WindowRestore,
} from '@fortawesome/free-regular-svg-icons';
// todo
// interface Icon1 extends IconDefinition {
//     icon1: boolean;
// }
// let icon1 = {
//     icon1: true,
//     ...faAddressBook,
// }

export {
    solid_AddressBook,
    solid_AddressCard,
    solid_Adjust,
    solid_AlignCenter,
    solid_AlignJustify,
    solid_AlignLeft,
    solid_AlignRight,
    solid_Allergies,
    solid_Ambulance,
    solid_AmericanSignLanguageInterpreting,
    solid_Anchor,
    solid_AngleDoubleDown,
    solid_AngleDoubleLeft,
    solid_AngleDoubleRight,
    solid_AngleDoubleUp,
    solid_AngleDown,
    solid_AngleLeft,
    solid_AngleRight,
    solid_AngleUp,
    solid_Archive,
    solid_ArrowAltCircleDown,
    solid_ArrowAltCircleLeft,
    solid_ArrowAltCircleRight,
    solid_ArrowAltCircleUp,
    solid_ArrowCircleDown,
    solid_ArrowCircleLeft,
    solid_ArrowCircleRight,
    solid_ArrowCircleUp,
    solid_ArrowDown,
    solid_ArrowLeft,
    solid_ArrowRight,
    solid_ArrowUp,
    solid_ArrowsAlt,
    solid_ArrowsAltH,
    solid_ArrowsAltV,
    solid_AssistiveListeningSystems,
    solid_Asterisk,
    solid_At,
    solid_AudioDescription,
    solid_Backward,
    solid_BalanceScale,
    solid_Ban,
    solid_BandAid,
    solid_Barcode,
    solid_Bars,
    solid_BaseballBall,
    solid_BasketballBall,
    solid_Bath,
    solid_BatteryEmpty,
    solid_BatteryFull,
    solid_BatteryHalf,
    solid_BatteryQuarter,
    solid_BatteryThreeQuarters,
    solid_Bed,
    solid_Beer,
    solid_Bell,
    solid_BellSlash,
    solid_Bicycle,
    solid_Binoculars,
    solid_BirthdayCake,
    solid_Blender,
    solid_Blind,
    solid_Bold,
    solid_Bolt,
    solid_Bomb,
    solid_Book,
    solid_BookOpen,
    solid_Bookmark,
    solid_BowlingBall,
    solid_Box,
    solid_BoxOpen,
    solid_Boxes,
    solid_Braille,
    solid_Briefcase,
    solid_BriefcaseMedical,
    solid_BroadcastTower,
    solid_Broom,
    solid_Bug,
    solid_Building,
    solid_Bullhorn,
    solid_Bullseye,
    solid_Burn,
    solid_Bus,
    solid_Calculator,
    solid_Calendar,
    solid_CalendarAlt,
    solid_CalendarCheck,
    solid_CalendarMinus,
    solid_CalendarPlus,
    solid_CalendarTimes,
    solid_Camera,
    solid_CameraRetro,
    solid_Capsules,
    solid_Car,
    solid_CaretDown,
    solid_CaretLeft,
    solid_CaretRight,
    solid_CaretSquareDown,
    solid_CaretSquareLeft,
    solid_CaretSquareRight,
    solid_CaretSquareUp,
    solid_CaretUp,
    solid_CartArrowDown,
    solid_CartPlus,
    solid_Certificate,
    solid_Chalkboard,
    solid_ChalkboardTeacher,
    solid_ChartArea,
    solid_ChartBar,
    solid_ChartLine,
    solid_ChartPie,
    solid_Check,
    solid_CheckCircle,
    solid_CheckSquare,
    solid_Chess,
    solid_ChessBishop,
    solid_ChessBoard,
    solid_ChessKing,
    solid_ChessKnight,
    solid_ChessPawn,
    solid_ChessQueen,
    solid_ChessRook,
    solid_ChevronCircleDown,
    solid_ChevronCircleLeft,
    solid_ChevronCircleRight,
    solid_ChevronCircleUp,
    solid_ChevronDown,
    solid_ChevronLeft,
    solid_ChevronRight,
    solid_ChevronUp,
    solid_Child,
    solid_Church,
    solid_Circle,
    solid_CircleNotch,
    solid_Clipboard,
    solid_ClipboardCheck,
    solid_ClipboardList,
    solid_Clock,
    solid_Clone,
    solid_ClosedCaptioning,
    solid_Cloud,
    solid_CloudDownloadAlt,
    solid_CloudUploadAlt,
    solid_Code,
    solid_CodeBranch,
    solid_Coffee,
    solid_Cog,
    solid_Cogs,
    solid_Coins,
    solid_Columns,
    solid_Comment,
    solid_CommentAlt,
    solid_CommentDots,
    solid_CommentSlash,
    solid_Comments,
    solid_CompactDisc,
    solid_Compass,
    solid_Compress,
    solid_Copy,
    solid_Copyright,
    solid_Couch,
    solid_CreditCard,
    solid_Crop,
    solid_Crosshairs,
    solid_Crow,
    solid_Crown,
    solid_Cube,
    solid_Cubes,
    solid_Cut,
    solid_Database,
    solid_Deaf,
    solid_Desktop,
    solid_Diagnoses,
    solid_Dice,
    solid_DiceFive,
    solid_DiceFour,
    solid_DiceOne,
    solid_DiceSix,
    solid_DiceThree,
    solid_DiceTwo,
    solid_Divide,
    solid_Dna,
    solid_DollarSign,
    solid_Dolly,
    solid_DollyFlatbed,
    solid_Donate,
    solid_DoorClosed,
    solid_DoorOpen,
    solid_DotCircle,
    solid_Dove,
    solid_Download,
    solid_Dumbbell,
    solid_Edit,
    solid_Eject,
    solid_EllipsisH,
    solid_EllipsisV,
    solid_Envelope,
    solid_EnvelopeOpen,
    solid_EnvelopeSquare,
    solid_Equals,
    solid_Eraser,
    solid_EuroSign,
    solid_ExchangeAlt,
    solid_Exclamation,
    solid_ExclamationCircle,
    solid_ExclamationTriangle,
    solid_Expand,
    solid_ExpandArrowsAlt,
    solid_ExternalLinkAlt,
    solid_ExternalLinkSquareAlt,
    solid_Eye,
    solid_EyeDropper,
    solid_EyeSlash,
    solid_FastBackward,
    solid_FastForward,
    solid_Fax,
    solid_Feather,
    solid_Female,
    solid_FighterJet,
    solid_File,
    solid_FileAlt,
    solid_FileArchive,
    solid_FileAudio,
    solid_FileCode,
    solid_FileExcel,
    solid_FileImage,
    solid_FileMedical,
    solid_FileMedicalAlt,
    solid_FilePdf,
    solid_FilePowerpoint,
    solid_FileVideo,
    solid_FileWord,
    solid_Film,
    solid_Filter,
    solid_Fire,
    solid_FireExtinguisher,
    solid_FirstAid,
    solid_Flag,
    solid_FlagCheckered,
    solid_Flask,
    solid_Folder,
    solid_FolderOpen,
    solid_Font,
    solid_FontAwesomeLogoFull,
    solid_FootballBall,
    solid_Forward,
    solid_Frog,
    solid_Frown,
    solid_Futbol,
    solid_Gamepad,
    solid_GasPump,
    solid_Gavel,
    solid_Gem,
    solid_Genderless,
    solid_Gift,
    solid_GlassMartini,
    solid_Glasses,
    solid_Globe,
    solid_GolfBall,
    solid_GraduationCap,
    solid_GreaterThan,
    solid_GreaterThanEqual,
    solid_HSquare,
    solid_HandHolding,
    solid_HandHoldingHeart,
    solid_HandHoldingUsd,
    solid_HandLizard,
    solid_HandPaper,
    solid_HandPeace,
    solid_HandPointDown,
    solid_HandPointLeft,
    solid_HandPointRight,
    solid_HandPointUp,
    solid_HandPointer,
    solid_HandRock,
    solid_HandScissors,
    solid_HandSpock,
    solid_Hands,
    solid_HandsHelping,
    solid_Handshake,
    solid_Hashtag,
    solid_Hdd,
    solid_Heading,
    solid_Headphones,
    solid_Heart,
    solid_Heartbeat,
    solid_Helicopter,
    solid_History,
    solid_HockeyPuck,
    solid_Home,
    solid_Hospital,
    solid_HospitalAlt,
    solid_HospitalSymbol,
    solid_Hourglass,
    solid_HourglassEnd,
    solid_HourglassHalf,
    solid_HourglassStart,
    solid_ICursor,
    solid_IdBadge,
    solid_IdCard,
    solid_IdCardAlt,
    solid_Image,
    solid_Images,
    solid_Inbox,
    solid_Indent,
    solid_Industry,
    solid_Infinity,
    solid_Info,
    solid_InfoCircle,
    solid_Italic,
    solid_Key,
    solid_Keyboard,
    solid_KiwiBird,
    solid_Language,
    solid_Laptop,
    solid_Leaf,
    solid_Lemon,
    solid_LessThan,
    solid_LessThanEqual,
    solid_LevelDownAlt,
    solid_LevelUpAlt,
    solid_LifeRing,
    solid_Lightbulb,
    solid_Link,
    solid_LiraSign,
    solid_List,
    solid_ListAlt,
    solid_ListOl,
    solid_ListUl,
    solid_LocationArrow,
    solid_Lock,
    solid_LockOpen,
    solid_LongArrowAltDown,
    solid_LongArrowAltLeft,
    solid_LongArrowAltRight,
    solid_LongArrowAltUp,
    solid_LowVision,
    solid_Magic,
    solid_Magnet,
    solid_Male,
    solid_Map,
    solid_MapMarker,
    solid_MapMarkerAlt,
    solid_MapPin,
    solid_MapSigns,
    solid_Mars,
    solid_MarsDouble,
    solid_MarsStroke,
    solid_MarsStrokeH,
    solid_MarsStrokeV,
    solid_Medkit,
    solid_Meh,
    solid_Memory,
    solid_Mercury,
    solid_Microchip,
    solid_Microphone,
    solid_MicrophoneAlt,
    solid_MicrophoneAltSlash,
    solid_MicrophoneSlash,
    solid_Minus,
    solid_MinusCircle,
    solid_MinusSquare,
    solid_Mobile,
    solid_MobileAlt,
    solid_MoneyBill,
    solid_MoneyBillAlt,
    solid_MoneyBillWave,
    solid_MoneyBillWaveAlt,
    solid_MoneyCheck,
    solid_MoneyCheckAlt,
    solid_Moon,
    solid_Motorcycle,
    solid_MousePointer,
    solid_Music,
    solid_Neuter,
    solid_Newspaper,
    solid_NotEqual,
    solid_NotesMedical,
    solid_ObjectGroup,
    solid_ObjectUngroup,
    solid_Outdent,
    solid_PaintBrush,
    solid_Palette,
    solid_Pallet,
    solid_PaperPlane,
    solid_Paperclip,
    solid_ParachuteBox,
    solid_Paragraph,
    solid_Parking,
    solid_Paste,
    solid_Pause,
    solid_PauseCircle,
    solid_Paw,
    solid_PenSquare,
    solid_PencilAlt,
    solid_PeopleCarry,
    solid_Percent,
    solid_Percentage,
    solid_Phone,
    solid_PhoneSlash,
    solid_PhoneSquare,
    solid_PhoneVolume,
    solid_PiggyBank,
    solid_Pills,
    solid_Plane,
    solid_Play,
    solid_PlayCircle,
    solid_Plug,
    solid_Plus,
    solid_PlusCircle,
    solid_PlusSquare,
    solid_Podcast,
    solid_Poo,
    solid_Portrait,
    solid_PoundSign,
    solid_PowerOff,
    solid_PrescriptionBottle,
    solid_PrescriptionBottleAlt,
    solid_Print,
    solid_Procedures,
    solid_ProjectDiagram,
    solid_PuzzlePiece,
    solid_Qrcode,
    solid_Question,
    solid_QuestionCircle,
    solid_Quidditch,
    solid_QuoteLeft,
    solid_QuoteRight,
    solid_Random,
    solid_Receipt,
    solid_Recycle,
    solid_Redo,
    solid_RedoAlt,
    solid_Registered,
    solid_Reply,
    solid_ReplyAll,
    solid_Retweet,
    solid_Ribbon,
    solid_Road,
    solid_Robot,
    solid_Rocket,
    solid_Rss,
    solid_RssSquare,
    solid_RubleSign,
    solid_Ruler,
    solid_RulerCombined,
    solid_RulerHorizontal,
    solid_RulerVertical,
    solid_RupeeSign,
    solid_Save,
    solid_School,
    solid_Screwdriver,
    solid_Search,
    solid_SearchMinus,
    solid_SearchPlus,
    solid_Seedling,
    solid_Server,
    solid_Share,
    solid_ShareAlt,
    solid_ShareAltSquare,
    solid_ShareSquare,
    solid_ShekelSign,
    solid_ShieldAlt,
    solid_Ship,
    solid_ShippingFast,
    solid_ShoePrints,
    solid_ShoppingBag,
    solid_ShoppingBasket,
    solid_ShoppingCart,
    solid_Shower,
    solid_Sign,
    solid_SignInAlt,
    solid_SignLanguage,
    solid_SignOutAlt,
    solid_Signal,
    solid_Sitemap,
    solid_Skull,
    solid_SlidersH,
    solid_Smile,
    solid_Smoking,
    solid_SmokingBan,
    solid_Snowflake,
    solid_Sort,
    solid_SortAlphaDown,
    solid_SortAlphaUp,
    solid_SortAmountDown,
    solid_SortAmountUp,
    solid_SortDown,
    solid_SortNumericDown,
    solid_SortNumericUp,
    solid_SortUp,
    solid_SpaceShuttle,
    solid_Spinner,
    solid_Square,
    solid_SquareFull,
    solid_Star,
    solid_StarHalf,
    solid_StepBackward,
    solid_StepForward,
    solid_Stethoscope,
    solid_StickyNote,
    solid_Stop,
    solid_StopCircle,
    solid_Stopwatch,
    solid_Store,
    solid_StoreAlt,
    solid_Stream,
    solid_StreetView,
    solid_Strikethrough,
    solid_Stroopwafel,
    solid_Subscript,
    solid_Subway,
    solid_Suitcase,
    solid_Sun,
    solid_Superscript,
    solid_Sync,
    solid_SyncAlt,
    solid_Syringe,
    solid_Table,
    solid_TableTennis,
    solid_Tablet,
    solid_TabletAlt,
    solid_Tablets,
    solid_TachometerAlt,
    solid_Tag,
    solid_Tags,
    solid_Tape,
    solid_Tasks,
    solid_Taxi,
    solid_Terminal,
    solid_TextHeight,
    solid_TextWidth,
    solid_Th,
    solid_ThLarge,
    solid_ThList,
    solid_Thermometer,
    solid_ThermometerEmpty,
    solid_ThermometerFull,
    solid_ThermometerHalf,
    solid_ThermometerQuarter,
    solid_ThermometerThreeQuarters,
    solid_ThumbsDown,
    solid_ThumbsUp,
    solid_Thumbtack,
    solid_TicketAlt,
    solid_Times,
    solid_TimesCircle,
    solid_Tint,
    solid_ToggleOff,
    solid_ToggleOn,
    solid_Toolbox,
    solid_Trademark,
    solid_Train,
    solid_Transgender,
    solid_TransgenderAlt,
    solid_Trash,
    solid_TrashAlt,
    solid_Tree,
    solid_Trophy,
    solid_Truck,
    solid_TruckLoading,
    solid_TruckMoving,
    solid_Tshirt,
    solid_Tty,
    solid_Tv,
    solid_Umbrella,
    solid_Underline,
    solid_Undo,
    solid_UndoAlt,
    solid_UniversalAccess,
    solid_University,
    solid_Unlink,
    solid_Unlock,
    solid_UnlockAlt,
    solid_Upload,
    solid_User,
    solid_UserAlt,
    solid_UserAltSlash,
    solid_UserAstronaut,
    solid_UserCheck,
    solid_UserCircle,
    solid_UserClock,
    solid_UserCog,
    solid_UserEdit,
    solid_UserFriends,
    solid_UserGraduate,
    solid_UserLock,
    solid_UserMd,
    solid_UserMinus,
    solid_UserNinja,
    solid_UserPlus,
    solid_UserSecret,
    solid_UserShield,
    solid_UserSlash,
    solid_UserTag,
    solid_UserTie,
    solid_UserTimes,
    solid_Users,
    solid_UsersCog,
    solid_UtensilSpoon,
    solid_Utensils,
    solid_Venus,
    solid_VenusDouble,
    solid_VenusMars,
    solid_Vial,
    solid_Vials,
    solid_Video,
    solid_VideoSlash,
    solid_VolleyballBall,
    solid_VolumeDown,
    solid_VolumeOff,
    solid_VolumeUp,
    solid_Walking,
    solid_Wallet,
    solid_Warehouse,
    solid_Weight,
    solid_Wheelchair,
    solid_Wifi,
    solid_WindowClose,
    solid_WindowMaximize,
    solid_WindowMinimize,
    solid_WindowRestore,
    solid_WineGlass,
    solid_WonSign,
    solid_Wrench,
    solid_XRay,
    solid_YenSign,
}
export {
    regular_AddressBook,
    regular_AddressCard,
    regular_ArrowAltCircleDown,
    regular_ArrowAltCircleLeft,
    regular_ArrowAltCircleRight,
    regular_ArrowAltCircleUp,
    regular_Bell,
    regular_BellSlash,
    regular_Bookmark,
    regular_Building,
    regular_Calendar,
    regular_CalendarAlt,
    regular_CalendarCheck,
    regular_CalendarMinus,
    regular_CalendarPlus,
    regular_CalendarTimes,
    regular_CaretSquareDown,
    regular_CaretSquareLeft,
    regular_CaretSquareRight,
    regular_CaretSquareUp,
    regular_ChartBar,
    regular_CheckCircle,
    regular_CheckSquare,
    regular_Circle,
    regular_Clipboard,
    regular_Clock,
    regular_Clone,
    regular_ClosedCaptioning,
    regular_Comment,
    regular_CommentAlt,
    regular_CommentDots,
    regular_Comments,
    regular_Compass,
    regular_Copy,
    regular_Copyright,
    regular_CreditCard,
    regular_DotCircle,
    regular_Edit,
    regular_Envelope,
    regular_EnvelopeOpen,
    regular_Eye,
    regular_EyeSlash,
    regular_File,
    regular_FileAlt,
    regular_FileArchive,
    regular_FileAudio,
    regular_FileCode,
    regular_FileExcel,
    regular_FileImage,
    regular_FilePdf,
    regular_FilePowerpoint,
    regular_FileVideo,
    regular_FileWord,
    regular_Flag,
    regular_Folder,
    regular_FolderOpen,
    regular_FontAwesomeLogoFull,
    regular_Frown,
    regular_Futbol,
    regular_Gem,
    regular_HandLizard,
    regular_HandPaper,
    regular_HandPeace,
    regular_HandPointDown,
    regular_HandPointLeft,
    regular_HandPointRight,
    regular_HandPointUp,
    regular_HandPointer,
    regular_HandRock,
    regular_HandScissors,
    regular_HandSpock,
    regular_Handshake,
    regular_Hdd,
    regular_Heart,
    regular_Hospital,
    regular_Hourglass,
    regular_IdBadge,
    regular_IdCard,
    regular_Image,
    regular_Images,
    regular_Keyboard,
    regular_Lemon,
    regular_LifeRing,
    regular_Lightbulb,
    regular_ListAlt,
    regular_Map,
    regular_Meh,
    regular_MinusSquare,
    regular_MoneyBillAlt,
    regular_Moon,
    regular_Newspaper,
    regular_ObjectGroup,
    regular_ObjectUngroup,
    regular_PaperPlane,
    regular_PauseCircle,
    regular_PlayCircle,
    regular_PlusSquare,
    regular_QuestionCircle,
    regular_Registered,
    regular_Save,
    regular_ShareSquare,
    regular_Smile,
    regular_Snowflake,
    regular_Square,
    regular_Star,
    regular_StarHalf,
    regular_StickyNote,
    regular_StopCircle,
    regular_Sun,
    regular_ThumbsDown,
    regular_ThumbsUp,
    regular_TimesCircle,
    regular_TrashAlt,
    regular_User,
    regular_UserCircle,
    regular_WindowClose,
    regular_WindowMaximize,
    regular_WindowMinimize,
    regular_WindowRestore,
}
