import {
    faAddressBook as iconAddressBook_solid,
    faAddressCard as iconAddressCard_solid,
    faAdjust as iconAdjust_solid,
    faAlignCenter as iconAlignCenter_solid,
    faAlignJustify as iconAlignJustify_solid,
    faAlignLeft as iconAlignLeft_solid,
    faAlignRight as iconAlignRight_solid,
    faAllergies as iconAllergies_solid,
    faAmbulance as iconAmbulance_solid,
    faAmericanSignLanguageInterpreting as iconAmericanSignLanguageInterpreting_solid,
    faAnchor as iconAnchor_solid,
    faAngleDoubleDown as iconAngleDoubleDown_solid,
    faAngleDoubleLeft as iconAngleDoubleLeft_solid,
    faAngleDoubleRight as iconAngleDoubleRight_solid,
    faAngleDoubleUp as iconAngleDoubleUp_solid,
    faAngleDown as iconAngleDown_solid,
    faAngleLeft as iconAngleLeft_solid,
    faAngleRight as iconAngleRight_solid,
    faAngleUp as iconAngleUp_solid,
    faArchive as iconArchive_solid,
    faArrowAltCircleDown as iconArrowAltCircleDown_solid,
    faArrowAltCircleLeft as iconArrowAltCircleLeft_solid,
    faArrowAltCircleRight as iconArrowAltCircleRight_solid,
    faArrowAltCircleUp as iconArrowAltCircleUp_solid,
    faArrowCircleDown as iconArrowCircleDown_solid,
    faArrowCircleLeft as iconArrowCircleLeft_solid,
    faArrowCircleRight as iconArrowCircleRight_solid,
    faArrowCircleUp as iconArrowCircleUp_solid,
    faArrowDown as iconArrowDown_solid,
    faArrowLeft as iconArrowLeft_solid,
    faArrowRight as iconArrowRight_solid,
    faArrowUp as iconArrowUp_solid,
    faArrowsAlt as iconArrowsAlt_solid,
    faArrowsAltH as iconArrowsAltH_solid,
    faArrowsAltV as iconArrowsAltV_solid,
    faAssistiveListeningSystems as iconAssistiveListeningSystems_solid,
    faAsterisk as iconAsterisk_solid,
    faAt as iconAt_solid,
    faAudioDescription as iconAudioDescription_solid,
    faBackward as iconBackward_solid,
    faBalanceScale as iconBalanceScale_solid,
    faBan as iconBan_solid,
    faBandAid as iconBandAid_solid,
    faBarcode as iconBarcode_solid,
    faBars as iconBars_solid,
    faBaseballBall as iconBaseballBall_solid,
    faBasketballBall as iconBasketballBall_solid,
    faBath as iconBath_solid,
    faBatteryEmpty as iconBatteryEmpty_solid,
    faBatteryFull as iconBatteryFull_solid,
    faBatteryHalf as iconBatteryHalf_solid,
    faBatteryQuarter as iconBatteryQuarter_solid,
    faBatteryThreeQuarters as iconBatteryThreeQuarters_solid,
    faBed as iconBed_solid,
    faBeer as iconBeer_solid,
    faBell as iconBell_solid,
    faBellSlash as iconBellSlash_solid,
    faBicycle as iconBicycle_solid,
    faBinoculars as iconBinoculars_solid,
    faBirthdayCake as iconBirthdayCake_solid,
    faBlender as iconBlender_solid,
    faBlind as iconBlind_solid,
    faBold as iconBold_solid,
    faBolt as iconBolt_solid,
    faBomb as iconBomb_solid,
    faBook as iconBook_solid,
    faBookOpen as iconBookOpen_solid,
    faBookmark as iconBookmark_solid,
    faBowlingBall as iconBowlingBall_solid,
    faBox as iconBox_solid,
    faBoxOpen as iconBoxOpen_solid,
    faBoxes as iconBoxes_solid,
    faBraille as iconBraille_solid,
    faBriefcase as iconBriefcase_solid,
    faBriefcaseMedical as iconBriefcaseMedical_solid,
    faBroadcastTower as iconBroadcastTower_solid,
    faBroom as iconBroom_solid,
    faBug as iconBug_solid,
    faBuilding as iconBuilding_solid,
    faBullhorn as iconBullhorn_solid,
    faBullseye as iconBullseye_solid,
    faBurn as iconBurn_solid,
    faBus as iconBus_solid,
    faCalculator as iconCalculator_solid,
    faCalendar as iconCalendar_solid,
    faCalendarAlt as iconCalendarAlt_solid,
    faCalendarCheck as iconCalendarCheck_solid,
    faCalendarMinus as iconCalendarMinus_solid,
    faCalendarPlus as iconCalendarPlus_solid,
    faCalendarTimes as iconCalendarTimes_solid,
    faCamera as iconCamera_solid,
    faCameraRetro as iconCameraRetro_solid,
    faCapsules as iconCapsules_solid,
    faCar as iconCar_solid,
    faCaretDown as iconCaretDown_solid,
    faCaretLeft as iconCaretLeft_solid,
    faCaretRight as iconCaretRight_solid,
    faCaretSquareDown as iconCaretSquareDown_solid,
    faCaretSquareLeft as iconCaretSquareLeft_solid,
    faCaretSquareRight as iconCaretSquareRight_solid,
    faCaretSquareUp as iconCaretSquareUp_solid,
    faCaretUp as iconCaretUp_solid,
    faCartArrowDown as iconCartArrowDown_solid,
    faCartPlus as iconCartPlus_solid,
    faCertificate as iconCertificate_solid,
    faChalkboard as iconChalkboard_solid,
    faChalkboardTeacher as iconChalkboardTeacher_solid,
    faChartArea as iconChartArea_solid,
    faChartBar as iconChartBar_solid,
    faChartLine as iconChartLine_solid,
    faChartPie as iconChartPie_solid,
    faCheck as iconCheck_solid,
    faCheckCircle as iconCheckCircle_solid,
    faCheckSquare as iconCheckSquare_solid,
    faChess as iconChess_solid,
    faChessBishop as iconChessBishop_solid,
    faChessBoard as iconChessBoard_solid,
    faChessKing as iconChessKing_solid,
    faChessKnight as iconChessKnight_solid,
    faChessPawn as iconChessPawn_solid,
    faChessQueen as iconChessQueen_solid,
    faChessRook as iconChessRook_solid,
    faChevronCircleDown as iconChevronCircleDown_solid,
    faChevronCircleLeft as iconChevronCircleLeft_solid,
    faChevronCircleRight as iconChevronCircleRight_solid,
    faChevronCircleUp as iconChevronCircleUp_solid,
    faChevronDown as iconChevronDown_solid,
    faChevronLeft as iconChevronLeft_solid,
    faChevronRight as iconChevronRight_solid,
    faChevronUp as iconChevronUp_solid,
    faChild as iconChild_solid,
    faChurch as iconChurch_solid,
    faCircle as iconCircle_solid,
    faCircleNotch as iconCircleNotch_solid,
    faClipboard as iconClipboard_solid,
    faClipboardCheck as iconClipboardCheck_solid,
    faClipboardList as iconClipboardList_solid,
    faClock as iconClock_solid,
    faClone as iconClone_solid,
    faClosedCaptioning as iconClosedCaptioning_solid,
    faCloud as iconCloud_solid,
    faCloudDownloadAlt as iconCloudDownloadAlt_solid,
    faCloudUploadAlt as iconCloudUploadAlt_solid,
    faCode as iconCode_solid,
    faCodeBranch as iconCodeBranch_solid,
    faCoffee as iconCoffee_solid,
    faCog as iconCog_solid,
    faCogs as iconCogs_solid,
    faCoins as iconCoins_solid,
    faColumns as iconColumns_solid,
    faComment as iconComment_solid,
    faCommentAlt as iconCommentAlt_solid,
    faCommentDots as iconCommentDots_solid,
    faCommentSlash as iconCommentSlash_solid,
    faComments as iconComments_solid,
    faCompactDisc as iconCompactDisc_solid,
    faCompass as iconCompass_solid,
    faCompress as iconCompress_solid,
    faCopy as iconCopy_solid,
    faCopyright as iconCopyright_solid,
    faCouch as iconCouch_solid,
    faCreditCard as iconCreditCard_solid,
    faCrop as iconCrop_solid,
    faCrosshairs as iconCrosshairs_solid,
    faCrow as iconCrow_solid,
    faCrown as iconCrown_solid,
    faCube as iconCube_solid,
    faCubes as iconCubes_solid,
    faCut as iconCut_solid,
    faDatabase as iconDatabase_solid,
    faDeaf as iconDeaf_solid,
    faDesktop as iconDesktop_solid,
    faDiagnoses as iconDiagnoses_solid,
    faDice as iconDice_solid,
    faDiceFive as iconDiceFive_solid,
    faDiceFour as iconDiceFour_solid,
    faDiceOne as iconDiceOne_solid,
    faDiceSix as iconDiceSix_solid,
    faDiceThree as iconDiceThree_solid,
    faDiceTwo as iconDiceTwo_solid,
    faDivide as iconDivide_solid,
    faDna as iconDna_solid,
    faDollarSign as iconDollarSign_solid,
    faDolly as iconDolly_solid,
    faDollyFlatbed as iconDollyFlatbed_solid,
    faDonate as iconDonate_solid,
    faDoorClosed as iconDoorClosed_solid,
    faDoorOpen as iconDoorOpen_solid,
    faDotCircle as iconDotCircle_solid,
    faDove as iconDove_solid,
    faDownload as iconDownload_solid,
    faDumbbell as iconDumbbell_solid,
    faEdit as iconEdit_solid,
    faEject as iconEject_solid,
    faEllipsisH as iconEllipsisH_solid,
    faEllipsisV as iconEllipsisV_solid,
    faEnvelope as iconEnvelope_solid,
    faEnvelopeOpen as iconEnvelopeOpen_solid,
    faEnvelopeSquare as iconEnvelopeSquare_solid,
    faEquals as iconEquals_solid,
    faEraser as iconEraser_solid,
    faEuroSign as iconEuroSign_solid,
    faExchangeAlt as iconExchangeAlt_solid,
    faExclamation as iconExclamation_solid,
    faExclamationCircle as iconExclamationCircle_solid,
    faExclamationTriangle as iconExclamationTriangle_solid,
    faExpand as iconExpand_solid,
    faExpandArrowsAlt as iconExpandArrowsAlt_solid,
    faExternalLinkAlt as iconExternalLinkAlt_solid,
    faExternalLinkSquareAlt as iconExternalLinkSquareAlt_solid,
    faEye as iconEye_solid,
    faEyeDropper as iconEyeDropper_solid,
    faEyeSlash as iconEyeSlash_solid,
    faFastBackward as iconFastBackward_solid,
    faFastForward as iconFastForward_solid,
    faFax as iconFax_solid,
    faFeather as iconFeather_solid,
    faFemale as iconFemale_solid,
    faFighterJet as iconFighterJet_solid,
    faFile as iconFile_solid,
    faFileAlt as iconFileAlt_solid,
    faFileArchive as iconFileArchive_solid,
    faFileAudio as iconFileAudio_solid,
    faFileCode as iconFileCode_solid,
    faFileExcel as iconFileExcel_solid,
    faFileImage as iconFileImage_solid,
    faFileMedical as iconFileMedical_solid,
    faFileMedicalAlt as iconFileMedicalAlt_solid,
    faFilePdf as iconFilePdf_solid,
    faFilePowerpoint as iconFilePowerpoint_solid,
    faFileVideo as iconFileVideo_solid,
    faFileWord as iconFileWord_solid,
    faFilm as iconFilm_solid,
    faFilter as iconFilter_solid,
    faFire as iconFire_solid,
    faFireExtinguisher as iconFireExtinguisher_solid,
    faFirstAid as iconFirstAid_solid,
    faFlag as iconFlag_solid,
    faFlagCheckered as iconFlagCheckered_solid,
    faFlask as iconFlask_solid,
    faFolder as iconFolder_solid,
    faFolderOpen as iconFolderOpen_solid,
    faFont as iconFont_solid,
    faFontAwesomeLogoFull as iconFontAwesomeLogoFull_solid,
    faFootballBall as iconFootballBall_solid,
    faForward as iconForward_solid,
    faFrog as iconFrog_solid,
    faFrown as iconFrown_solid,
    faFutbol as iconFutbol_solid,
    faGamepad as iconGamepad_solid,
    faGasPump as iconGasPump_solid,
    faGavel as iconGavel_solid,
    faGem as iconGem_solid,
    faGenderless as iconGenderless_solid,
    faGift as iconGift_solid,
    faGlassMartini as iconGlassMartini_solid,
    faGlasses as iconGlasses_solid,
    faGlobe as iconGlobe_solid,
    faGolfBall as iconGolfBall_solid,
    faGraduationCap as iconGraduationCap_solid,
    faGreaterThan as iconGreaterThan_solid,
    faGreaterThanEqual as iconGreaterThanEqual_solid,
    faHSquare as iconHSquare_solid,
    faHandHolding as iconHandHolding_solid,
    faHandHoldingHeart as iconHandHoldingHeart_solid,
    faHandHoldingUsd as iconHandHoldingUsd_solid,
    faHandLizard as iconHandLizard_solid,
    faHandPaper as iconHandPaper_solid,
    faHandPeace as iconHandPeace_solid,
    faHandPointDown as iconHandPointDown_solid,
    faHandPointLeft as iconHandPointLeft_solid,
    faHandPointRight as iconHandPointRight_solid,
    faHandPointUp as iconHandPointUp_solid,
    faHandPointer as iconHandPointer_solid,
    faHandRock as iconHandRock_solid,
    faHandScissors as iconHandScissors_solid,
    faHandSpock as iconHandSpock_solid,
    faHands as iconHands_solid,
    faHandsHelping as iconHandsHelping_solid,
    faHandshake as iconHandshake_solid,
    faHashtag as iconHashtag_solid,
    faHdd as iconHdd_solid,
    faHeading as iconHeading_solid,
    faHeadphones as iconHeadphones_solid,
    faHeart as iconHeart_solid,
    faHeartbeat as iconHeartbeat_solid,
    faHelicopter as iconHelicopter_solid,
    faHistory as iconHistory_solid,
    faHockeyPuck as iconHockeyPuck_solid,
    faHome as iconHome_solid,
    faHospital as iconHospital_solid,
    faHospitalAlt as iconHospitalAlt_solid,
    faHospitalSymbol as iconHospitalSymbol_solid,
    faHourglass as iconHourglass_solid,
    faHourglassEnd as iconHourglassEnd_solid,
    faHourglassHalf as iconHourglassHalf_solid,
    faHourglassStart as iconHourglassStart_solid,
    faICursor as iconICursor_solid,
    faIdBadge as iconIdBadge_solid,
    faIdCard as iconIdCard_solid,
    faIdCardAlt as iconIdCardAlt_solid,
    faImage as iconImage_solid,
    faImages as iconImages_solid,
    faInbox as iconInbox_solid,
    faIndent as iconIndent_solid,
    faIndustry as iconIndustry_solid,
    faInfinity as iconInfinity_solid,
    faInfo as iconInfo_solid,
    faInfoCircle as iconInfoCircle_solid,
    faItalic as iconItalic_solid,
    faKey as iconKey_solid,
    faKeyboard as iconKeyboard_solid,
    faKiwiBird as iconKiwiBird_solid,
    faLanguage as iconLanguage_solid,
    faLaptop as iconLaptop_solid,
    faLeaf as iconLeaf_solid,
    faLemon as iconLemon_solid,
    faLessThan as iconLessThan_solid,
    faLessThanEqual as iconLessThanEqual_solid,
    faLevelDownAlt as iconLevelDownAlt_solid,
    faLevelUpAlt as iconLevelUpAlt_solid,
    faLifeRing as iconLifeRing_solid,
    faLightbulb as iconLightbulb_solid,
    faLink as iconLink_solid,
    faLiraSign as iconLiraSign_solid,
    faList as iconList_solid,
    faListAlt as iconListAlt_solid,
    faListOl as iconListOl_solid,
    faListUl as iconListUl_solid,
    faLocationArrow as iconLocationArrow_solid,
    faLock as iconLock_solid,
    faLockOpen as iconLockOpen_solid,
    faLongArrowAltDown as iconLongArrowAltDown_solid,
    faLongArrowAltLeft as iconLongArrowAltLeft_solid,
    faLongArrowAltRight as iconLongArrowAltRight_solid,
    faLongArrowAltUp as iconLongArrowAltUp_solid,
    faLowVision as iconLowVision_solid,
    faMagic as iconMagic_solid,
    faMagnet as iconMagnet_solid,
    faMale as iconMale_solid,
    faMap as iconMap_solid,
    faMapMarker as iconMapMarker_solid,
    faMapMarkerAlt as iconMapMarkerAlt_solid,
    faMapPin as iconMapPin_solid,
    faMapSigns as iconMapSigns_solid,
    faMars as iconMars_solid,
    faMarsDouble as iconMarsDouble_solid,
    faMarsStroke as iconMarsStroke_solid,
    faMarsStrokeH as iconMarsStrokeH_solid,
    faMarsStrokeV as iconMarsStrokeV_solid,
    faMedkit as iconMedkit_solid,
    faMeh as iconMeh_solid,
    faMemory as iconMemory_solid,
    faMercury as iconMercury_solid,
    faMicrochip as iconMicrochip_solid,
    faMicrophone as iconMicrophone_solid,
    faMicrophoneAlt as iconMicrophoneAlt_solid,
    faMicrophoneAltSlash as iconMicrophoneAltSlash_solid,
    faMicrophoneSlash as iconMicrophoneSlash_solid,
    faMinus as iconMinus_solid,
    faMinusCircle as iconMinusCircle_solid,
    faMinusSquare as iconMinusSquare_solid,
    faMobile as iconMobile_solid,
    faMobileAlt as iconMobileAlt_solid,
    faMoneyBill as iconMoneyBill_solid,
    faMoneyBillAlt as iconMoneyBillAlt_solid,
    faMoneyBillWave as iconMoneyBillWave_solid,
    faMoneyBillWaveAlt as iconMoneyBillWaveAlt_solid,
    faMoneyCheck as iconMoneyCheck_solid,
    faMoneyCheckAlt as iconMoneyCheckAlt_solid,
    faMoon as iconMoon_solid,
    faMotorcycle as iconMotorcycle_solid,
    faMousePointer as iconMousePointer_solid,
    faMusic as iconMusic_solid,
    faNeuter as iconNeuter_solid,
    faNewspaper as iconNewspaper_solid,
    faNotEqual as iconNotEqual_solid,
    faNotesMedical as iconNotesMedical_solid,
    faObjectGroup as iconObjectGroup_solid,
    faObjectUngroup as iconObjectUngroup_solid,
    faOutdent as iconOutdent_solid,
    faPaintBrush as iconPaintBrush_solid,
    faPalette as iconPalette_solid,
    faPallet as iconPallet_solid,
    faPaperPlane as iconPaperPlane_solid,
    faPaperclip as iconPaperclip_solid,
    faParachuteBox as iconParachuteBox_solid,
    faParagraph as iconParagraph_solid,
    faParking as iconParking_solid,
    faPaste as iconPaste_solid,
    faPause as iconPause_solid,
    faPauseCircle as iconPauseCircle_solid,
    faPaw as iconPaw_solid,
    faPenSquare as iconPenSquare_solid,
    faPencilAlt as iconPencilAlt_solid,
    faPeopleCarry as iconPeopleCarry_solid,
    faPercent as iconPercent_solid,
    faPercentage as iconPercentage_solid,
    faPhone as iconPhone_solid,
    faPhoneSlash as iconPhoneSlash_solid,
    faPhoneSquare as iconPhoneSquare_solid,
    faPhoneVolume as iconPhoneVolume_solid,
    faPiggyBank as iconPiggyBank_solid,
    faPills as iconPills_solid,
    faPlane as iconPlane_solid,
    faPlay as iconPlay_solid,
    faPlayCircle as iconPlayCircle_solid,
    faPlug as iconPlug_solid,
    faPlus as iconPlus_solid,
    faPlusCircle as iconPlusCircle_solid,
    faPlusSquare as iconPlusSquare_solid,
    faPodcast as iconPodcast_solid,
    faPoo as iconPoo_solid,
    faPortrait as iconPortrait_solid,
    faPoundSign as iconPoundSign_solid,
    faPowerOff as iconPowerOff_solid,
    faPrescriptionBottle as iconPrescriptionBottle_solid,
    faPrescriptionBottleAlt as iconPrescriptionBottleAlt_solid,
    faPrint as iconPrint_solid,
    faProcedures as iconProcedures_solid,
    faProjectDiagram as iconProjectDiagram_solid,
    faPuzzlePiece as iconPuzzlePiece_solid,
    faQrcode as iconQrcode_solid,
    faQuestion as iconQuestion_solid,
    faQuestionCircle as iconQuestionCircle_solid,
    faQuidditch as iconQuidditch_solid,
    faQuoteLeft as iconQuoteLeft_solid,
    faQuoteRight as iconQuoteRight_solid,
    faRandom as iconRandom_solid,
    faReceipt as iconReceipt_solid,
    faRecycle as iconRecycle_solid,
    faRedo as iconRedo_solid,
    faRedoAlt as iconRedoAlt_solid,
    faRegistered as iconRegistered_solid,
    faReply as iconReply_solid,
    faReplyAll as iconReplyAll_solid,
    faRetweet as iconRetweet_solid,
    faRibbon as iconRibbon_solid,
    faRoad as iconRoad_solid,
    faRobot as iconRobot_solid,
    faRocket as iconRocket_solid,
    faRss as iconRss_solid,
    faRssSquare as iconRssSquare_solid,
    faRubleSign as iconRubleSign_solid,
    faRuler as iconRuler_solid,
    faRulerCombined as iconRulerCombined_solid,
    faRulerHorizontal as iconRulerHorizontal_solid,
    faRulerVertical as iconRulerVertical_solid,
    faRupeeSign as iconRupeeSign_solid,
    faSave as iconSave_solid,
    faSchool as iconSchool_solid,
    faScrewdriver as iconScrewdriver_solid,
    faSearch as iconSearch_solid,
    faSearchMinus as iconSearchMinus_solid,
    faSearchPlus as iconSearchPlus_solid,
    faSeedling as iconSeedling_solid,
    faServer as iconServer_solid,
    faShare as iconShare_solid,
    faShareAlt as iconShareAlt_solid,
    faShareAltSquare as iconShareAltSquare_solid,
    faShareSquare as iconShareSquare_solid,
    faShekelSign as iconShekelSign_solid,
    faShieldAlt as iconShieldAlt_solid,
    faShip as iconShip_solid,
    faShippingFast as iconShippingFast_solid,
    faShoePrints as iconShoePrints_solid,
    faShoppingBag as iconShoppingBag_solid,
    faShoppingBasket as iconShoppingBasket_solid,
    faShoppingCart as iconShoppingCart_solid,
    faShower as iconShower_solid,
    faSign as iconSign_solid,
    faSignInAlt as iconSignInAlt_solid,
    faSignLanguage as iconSignLanguage_solid,
    faSignOutAlt as iconSignOutAlt_solid,
    faSignal as iconSignal_solid,
    faSitemap as iconSitemap_solid,
    faSkull as iconSkull_solid,
    faSlidersH as iconSlidersH_solid,
    faSmile as iconSmile_solid,
    faSmoking as iconSmoking_solid,
    faSmokingBan as iconSmokingBan_solid,
    faSnowflake as iconSnowflake_solid,
    faSort as iconSort_solid,
    faSortAlphaDown as iconSortAlphaDown_solid,
    faSortAlphaUp as iconSortAlphaUp_solid,
    faSortAmountDown as iconSortAmountDown_solid,
    faSortAmountUp as iconSortAmountUp_solid,
    faSortDown as iconSortDown_solid,
    faSortNumericDown as iconSortNumericDown_solid,
    faSortNumericUp as iconSortNumericUp_solid,
    faSortUp as iconSortUp_solid,
    faSpaceShuttle as iconSpaceShuttle_solid,
    faSpinner as iconSpinner_solid,
    faSquare as iconSquare_solid,
    faSquareFull as iconSquareFull_solid,
    faStar as iconStar_solid,
    faStarHalf as iconStarHalf_solid,
    faStepBackward as iconStepBackward_solid,
    faStepForward as iconStepForward_solid,
    faStethoscope as iconStethoscope_solid,
    faStickyNote as iconStickyNote_solid,
    faStop as iconStop_solid,
    faStopCircle as iconStopCircle_solid,
    faStopwatch as iconStopwatch_solid,
    faStore as iconStore_solid,
    faStoreAlt as iconStoreAlt_solid,
    faStream as iconStream_solid,
    faStreetView as iconStreetView_solid,
    faStrikethrough as iconStrikethrough_solid,
    faStroopwafel as iconStroopwafel_solid,
    faSubscript as iconSubscript_solid,
    faSubway as iconSubway_solid,
    faSuitcase as iconSuitcase_solid,
    faSun as iconSun_solid,
    faSuperscript as iconSuperscript_solid,
    faSync as iconSync_solid,
    faSyncAlt as iconSyncAlt_solid,
    faSyringe as iconSyringe_solid,
    faTable as iconTable_solid,
    faTableTennis as iconTableTennis_solid,
    faTablet as iconTablet_solid,
    faTabletAlt as iconTabletAlt_solid,
    faTablets as iconTablets_solid,
    faTachometerAlt as iconTachometerAlt_solid,
    faTag as iconTag_solid,
    faTags as iconTags_solid,
    faTape as iconTape_solid,
    faTasks as iconTasks_solid,
    faTaxi as iconTaxi_solid,
    faTerminal as iconTerminal_solid,
    faTextHeight as iconTextHeight_solid,
    faTextWidth as iconTextWidth_solid,
    faTh as iconTh_solid,
    faThLarge as iconThLarge_solid,
    faThList as iconThList_solid,
    faThermometer as iconThermometer_solid,
    faThermometerEmpty as iconThermometerEmpty_solid,
    faThermometerFull as iconThermometerFull_solid,
    faThermometerHalf as iconThermometerHalf_solid,
    faThermometerQuarter as iconThermometerQuarter_solid,
    faThermometerThreeQuarters as iconThermometerThreeQuarters_solid,
    faThumbsDown as iconThumbsDown_solid,
    faThumbsUp as iconThumbsUp_solid,
    faThumbtack as iconThumbtack_solid,
    faTicketAlt as iconTicketAlt_solid,
    faTimes as iconTimes_solid,
    faTimesCircle as iconTimesCircle_solid,
    faTint as iconTint_solid,
    faToggleOff as iconToggleOff_solid,
    faToggleOn as iconToggleOn_solid,
    faToolbox as iconToolbox_solid,
    faTrademark as iconTrademark_solid,
    faTrain as iconTrain_solid,
    faTransgender as iconTransgender_solid,
    faTransgenderAlt as iconTransgenderAlt_solid,
    faTrash as iconTrash_solid,
    faTrashAlt as iconTrashAlt_solid,
    faTree as iconTree_solid,
    faTrophy as iconTrophy_solid,
    faTruck as iconTruck_solid,
    faTruckLoading as iconTruckLoading_solid,
    faTruckMoving as iconTruckMoving_solid,
    faTshirt as iconTshirt_solid,
    faTty as iconTty_solid,
    faTv as iconTv_solid,
    faUmbrella as iconUmbrella_solid,
    faUnderline as iconUnderline_solid,
    faUndo as iconUndo_solid,
    faUndoAlt as iconUndoAlt_solid,
    faUniversalAccess as iconUniversalAccess_solid,
    faUniversity as iconUniversity_solid,
    faUnlink as iconUnlink_solid,
    faUnlock as iconUnlock_solid,
    faUnlockAlt as iconUnlockAlt_solid,
    faUpload as iconUpload_solid,
    faUser as iconUser_solid,
    faUserAlt as iconUserAlt_solid,
    faUserAltSlash as iconUserAltSlash_solid,
    faUserAstronaut as iconUserAstronaut_solid,
    faUserCheck as iconUserCheck_solid,
    faUserCircle as iconUserCircle_solid,
    faUserClock as iconUserClock_solid,
    faUserCog as iconUserCog_solid,
    faUserEdit as iconUserEdit_solid,
    faUserFriends as iconUserFriends_solid,
    faUserGraduate as iconUserGraduate_solid,
    faUserLock as iconUserLock_solid,
    faUserMd as iconUserMd_solid,
    faUserMinus as iconUserMinus_solid,
    faUserNinja as iconUserNinja_solid,
    faUserPlus as iconUserPlus_solid,
    faUserSecret as iconUserSecret_solid,
    faUserShield as iconUserShield_solid,
    faUserSlash as iconUserSlash_solid,
    faUserTag as iconUserTag_solid,
    faUserTie as iconUserTie_solid,
    faUserTimes as iconUserTimes_solid,
    faUsers as iconUsers_solid,
    faUsersCog as iconUsersCog_solid,
    faUtensilSpoon as iconUtensilSpoon_solid,
    faUtensils as iconUtensils_solid,
    faVenus as iconVenus_solid,
    faVenusDouble as iconVenusDouble_solid,
    faVenusMars as iconVenusMars_solid,
    faVial as iconVial_solid,
    faVials as iconVials_solid,
    faVideo as iconVideo_solid,
    faVideoSlash as iconVideoSlash_solid,
    faVolleyballBall as iconVolleyballBall_solid,
    faVolumeDown as iconVolumeDown_solid,
    faVolumeOff as iconVolumeOff_solid,
    faVolumeUp as iconVolumeUp_solid,
    faWalking as iconWalking_solid,
    faWallet as iconWallet_solid,
    faWarehouse as iconWarehouse_solid,
    faWeight as iconWeight_solid,
    faWheelchair as iconWheelchair_solid,
    faWifi as iconWifi_solid,
    faWindowClose as iconWindowClose_solid,
    faWindowMaximize as iconWindowMaximize_solid,
    faWindowMinimize as iconWindowMinimize_solid,
    faWindowRestore as iconWindowRestore_solid,
    faWineGlass as iconWineGlass_solid,
    faWonSign as iconWonSign_solid,
    faWrench as iconWrench_solid,
    faXRay as iconXRay_solid,
    faYenSign as iconYenSign_solid,
} from '@fortawesome/free-solid-svg-icons';
import {
    faAddressBook as iconAddressBook_regular,
    faAddressCard as iconAddressCard_regular,
    faArrowAltCircleDown as iconArrowAltCircleDown_regular,
    faArrowAltCircleLeft as iconArrowAltCircleLeft_regular,
    faArrowAltCircleRight as iconArrowAltCircleRight_regular,
    faArrowAltCircleUp as iconArrowAltCircleUp_regular,
    faBell as iconBell_regular,
    faBellSlash as iconBellSlash_regular,
    faBookmark as iconBookmark_regular,
    faBuilding as iconBuilding_regular,
    faCalendar as iconCalendar_regular,
    faCalendarAlt as iconCalendarAlt_regular,
    faCalendarCheck as iconCalendarCheck_regular,
    faCalendarMinus as iconCalendarMinus_regular,
    faCalendarPlus as iconCalendarPlus_regular,
    faCalendarTimes as iconCalendarTimes_regular,
    faCaretSquareDown as iconCaretSquareDown_regular,
    faCaretSquareLeft as iconCaretSquareLeft_regular,
    faCaretSquareRight as iconCaretSquareRight_regular,
    faCaretSquareUp as iconCaretSquareUp_regular,
    faChartBar as iconChartBar_regular,
    faCheckCircle as iconCheckCircle_regular,
    faCheckSquare as iconCheckSquare_regular,
    faCircle as iconCircle_regular,
    faClipboard as iconClipboard_regular,
    faClock as iconClock_regular,
    faClone as iconClone_regular,
    faClosedCaptioning as iconClosedCaptioning_regular,
    faComment as iconComment_regular,
    faCommentAlt as iconCommentAlt_regular,
    faCommentDots as iconCommentDots_regular,
    faComments as iconComments_regular,
    faCompass as iconCompass_regular,
    faCopy as iconCopy_regular,
    faCopyright as iconCopyright_regular,
    faCreditCard as iconCreditCard_regular,
    faDotCircle as iconDotCircle_regular,
    faEdit as iconEdit_regular,
    faEnvelope as iconEnvelope_regular,
    faEnvelopeOpen as iconEnvelopeOpen_regular,
    faEye as iconEye_regular,
    faEyeSlash as iconEyeSlash_regular,
    faFile as iconFile_regular,
    faFileAlt as iconFileAlt_regular,
    faFileArchive as iconFileArchive_regular,
    faFileAudio as iconFileAudio_regular,
    faFileCode as iconFileCode_regular,
    faFileExcel as iconFileExcel_regular,
    faFileImage as iconFileImage_regular,
    faFilePdf as iconFilePdf_regular,
    faFilePowerpoint as iconFilePowerpoint_regular,
    faFileVideo as iconFileVideo_regular,
    faFileWord as iconFileWord_regular,
    faFlag as iconFlag_regular,
    faFolder as iconFolder_regular,
    faFolderOpen as iconFolderOpen_regular,
    faFontAwesomeLogoFull as iconFontAwesomeLogoFull_regular,
    faFrown as iconFrown_regular,
    faFutbol as iconFutbol_regular,
    faGem as iconGem_regular,
    faHandLizard as iconHandLizard_regular,
    faHandPaper as iconHandPaper_regular,
    faHandPeace as iconHandPeace_regular,
    faHandPointDown as iconHandPointDown_regular,
    faHandPointLeft as iconHandPointLeft_regular,
    faHandPointRight as iconHandPointRight_regular,
    faHandPointUp as iconHandPointUp_regular,
    faHandPointer as iconHandPointer_regular,
    faHandRock as iconHandRock_regular,
    faHandScissors as iconHandScissors_regular,
    faHandSpock as iconHandSpock_regular,
    faHandshake as iconHandshake_regular,
    faHdd as iconHdd_regular,
    faHeart as iconHeart_regular,
    faHospital as iconHospital_regular,
    faHourglass as iconHourglass_regular,
    faIdBadge as iconIdBadge_regular,
    faIdCard as iconIdCard_regular,
    faImage as iconImage_regular,
    faImages as iconImages_regular,
    faKeyboard as iconKeyboard_regular,
    faLemon as iconLemon_regular,
    faLifeRing as iconLifeRing_regular,
    faLightbulb as iconLightbulb_regular,
    faListAlt as iconListAlt_regular,
    faMap as iconMap_regular,
    faMeh as iconMeh_regular,
    faMinusSquare as iconMinusSquare_regular,
    faMoneyBillAlt as iconMoneyBillAlt_regular,
    faMoon as iconMoon_regular,
    faNewspaper as iconNewspaper_regular,
    faObjectGroup as iconObjectGroup_regular,
    faObjectUngroup as iconObjectUngroup_regular,
    faPaperPlane as iconPaperPlane_regular,
    faPauseCircle as iconPauseCircle_regular,
    faPlayCircle as iconPlayCircle_regular,
    faPlusSquare as iconPlusSquare_regular,
    faQuestionCircle as iconQuestionCircle_regular,
    faRegistered as iconRegistered_regular,
    faSave as iconSave_regular,
    faShareSquare as iconShareSquare_regular,
    faSmile as iconSmile_regular,
    faSnowflake as iconSnowflake_regular,
    faSquare as iconSquare_regular,
    faStar as iconStar_regular,
    faStarHalf as iconStarHalf_regular,
    faStickyNote as iconStickyNote_regular,
    faStopCircle as iconStopCircle_regular,
    faSun as iconSun_regular,
    faThumbsDown as iconThumbsDown_regular,
    faThumbsUp as iconThumbsUp_regular,
    faTimesCircle as iconTimesCircle_regular,
    faTrashAlt as iconTrashAlt_regular,
    faUser as iconUser_regular,
    faUserCircle as iconUserCircle_regular,
    faWindowClose as iconWindowClose_regular,
    faWindowMaximize as iconWindowMaximize_regular,
    faWindowMinimize as iconWindowMinimize_regular,
    faWindowRestore as iconWindowRestore_regular,
} from '@fortawesome/free-regular-svg-icons';

export {
    iconAddressBook_solid,
    iconAddressCard_solid,
    iconAdjust_solid,
    iconAlignCenter_solid,
    iconAlignJustify_solid,
    iconAlignLeft_solid,
    iconAlignRight_solid,
    iconAllergies_solid,
    iconAmbulance_solid,
    iconAmericanSignLanguageInterpreting_solid,
    iconAnchor_solid,
    iconAngleDoubleDown_solid,
    iconAngleDoubleLeft_solid,
    iconAngleDoubleRight_solid,
    iconAngleDoubleUp_solid,
    iconAngleDown_solid,
    iconAngleLeft_solid,
    iconAngleRight_solid,
    iconAngleUp_solid,
    iconArchive_solid,
    iconArrowAltCircleDown_solid,
    iconArrowAltCircleLeft_solid,
    iconArrowAltCircleRight_solid,
    iconArrowAltCircleUp_solid,
    iconArrowCircleDown_solid,
    iconArrowCircleLeft_solid,
    iconArrowCircleRight_solid,
    iconArrowCircleUp_solid,
    iconArrowDown_solid,
    iconArrowLeft_solid,
    iconArrowRight_solid,
    iconArrowUp_solid,
    iconArrowsAlt_solid,
    iconArrowsAltH_solid,
    iconArrowsAltV_solid,
    iconAssistiveListeningSystems_solid,
    iconAsterisk_solid,
    iconAt_solid,
    iconAudioDescription_solid,
    iconBackward_solid,
    iconBalanceScale_solid,
    iconBan_solid,
    iconBandAid_solid,
    iconBarcode_solid,
    iconBars_solid,
    iconBaseballBall_solid,
    iconBasketballBall_solid,
    iconBath_solid,
    iconBatteryEmpty_solid,
    iconBatteryFull_solid,
    iconBatteryHalf_solid,
    iconBatteryQuarter_solid,
    iconBatteryThreeQuarters_solid,
    iconBed_solid,
    iconBeer_solid,
    iconBell_solid,
    iconBellSlash_solid,
    iconBicycle_solid,
    iconBinoculars_solid,
    iconBirthdayCake_solid,
    iconBlender_solid,
    iconBlind_solid,
    iconBold_solid,
    iconBolt_solid,
    iconBomb_solid,
    iconBook_solid,
    iconBookOpen_solid,
    iconBookmark_solid,
    iconBowlingBall_solid,
    iconBox_solid,
    iconBoxOpen_solid,
    iconBoxes_solid,
    iconBraille_solid,
    iconBriefcase_solid,
    iconBriefcaseMedical_solid,
    iconBroadcastTower_solid,
    iconBroom_solid,
    iconBug_solid,
    iconBuilding_solid,
    iconBullhorn_solid,
    iconBullseye_solid,
    iconBurn_solid,
    iconBus_solid,
    iconCalculator_solid,
    iconCalendar_solid,
    iconCalendarAlt_solid,
    iconCalendarCheck_solid,
    iconCalendarMinus_solid,
    iconCalendarPlus_solid,
    iconCalendarTimes_solid,
    iconCamera_solid,
    iconCameraRetro_solid,
    iconCapsules_solid,
    iconCar_solid,
    iconCaretDown_solid,
    iconCaretLeft_solid,
    iconCaretRight_solid,
    iconCaretSquareDown_solid,
    iconCaretSquareLeft_solid,
    iconCaretSquareRight_solid,
    iconCaretSquareUp_solid,
    iconCaretUp_solid,
    iconCartArrowDown_solid,
    iconCartPlus_solid,
    iconCertificate_solid,
    iconChalkboard_solid,
    iconChalkboardTeacher_solid,
    iconChartArea_solid,
    iconChartBar_solid,
    iconChartLine_solid,
    iconChartPie_solid,
    iconCheck_solid,
    iconCheckCircle_solid,
    iconCheckSquare_solid,
    iconChess_solid,
    iconChessBishop_solid,
    iconChessBoard_solid,
    iconChessKing_solid,
    iconChessKnight_solid,
    iconChessPawn_solid,
    iconChessQueen_solid,
    iconChessRook_solid,
    iconChevronCircleDown_solid,
    iconChevronCircleLeft_solid,
    iconChevronCircleRight_solid,
    iconChevronCircleUp_solid,
    iconChevronDown_solid,
    iconChevronLeft_solid,
    iconChevronRight_solid,
    iconChevronUp_solid,
    iconChild_solid,
    iconChurch_solid,
    iconCircle_solid,
    iconCircleNotch_solid,
    iconClipboard_solid,
    iconClipboardCheck_solid,
    iconClipboardList_solid,
    iconClock_solid,
    iconClone_solid,
    iconClosedCaptioning_solid,
    iconCloud_solid,
    iconCloudDownloadAlt_solid,
    iconCloudUploadAlt_solid,
    iconCode_solid,
    iconCodeBranch_solid,
    iconCoffee_solid,
    iconCog_solid,
    iconCogs_solid,
    iconCoins_solid,
    iconColumns_solid,
    iconComment_solid,
    iconCommentAlt_solid,
    iconCommentDots_solid,
    iconCommentSlash_solid,
    iconComments_solid,
    iconCompactDisc_solid,
    iconCompass_solid,
    iconCompress_solid,
    iconCopy_solid,
    iconCopyright_solid,
    iconCouch_solid,
    iconCreditCard_solid,
    iconCrop_solid,
    iconCrosshairs_solid,
    iconCrow_solid,
    iconCrown_solid,
    iconCube_solid,
    iconCubes_solid,
    iconCut_solid,
    iconDatabase_solid,
    iconDeaf_solid,
    iconDesktop_solid,
    iconDiagnoses_solid,
    iconDice_solid,
    iconDiceFive_solid,
    iconDiceFour_solid,
    iconDiceOne_solid,
    iconDiceSix_solid,
    iconDiceThree_solid,
    iconDiceTwo_solid,
    iconDivide_solid,
    iconDna_solid,
    iconDollarSign_solid,
    iconDolly_solid,
    iconDollyFlatbed_solid,
    iconDonate_solid,
    iconDoorClosed_solid,
    iconDoorOpen_solid,
    iconDotCircle_solid,
    iconDove_solid,
    iconDownload_solid,
    iconDumbbell_solid,
    iconEdit_solid,
    iconEject_solid,
    iconEllipsisH_solid,
    iconEllipsisV_solid,
    iconEnvelope_solid,
    iconEnvelopeOpen_solid,
    iconEnvelopeSquare_solid,
    iconEquals_solid,
    iconEraser_solid,
    iconEuroSign_solid,
    iconExchangeAlt_solid,
    iconExclamation_solid,
    iconExclamationCircle_solid,
    iconExclamationTriangle_solid,
    iconExpand_solid,
    iconExpandArrowsAlt_solid,
    iconExternalLinkAlt_solid,
    iconExternalLinkSquareAlt_solid,
    iconEye_solid,
    iconEyeDropper_solid,
    iconEyeSlash_solid,
    iconFastBackward_solid,
    iconFastForward_solid,
    iconFax_solid,
    iconFeather_solid,
    iconFemale_solid,
    iconFighterJet_solid,
    iconFile_solid,
    iconFileAlt_solid,
    iconFileArchive_solid,
    iconFileAudio_solid,
    iconFileCode_solid,
    iconFileExcel_solid,
    iconFileImage_solid,
    iconFileMedical_solid,
    iconFileMedicalAlt_solid,
    iconFilePdf_solid,
    iconFilePowerpoint_solid,
    iconFileVideo_solid,
    iconFileWord_solid,
    iconFilm_solid,
    iconFilter_solid,
    iconFire_solid,
    iconFireExtinguisher_solid,
    iconFirstAid_solid,
    iconFlag_solid,
    iconFlagCheckered_solid,
    iconFlask_solid,
    iconFolder_solid,
    iconFolderOpen_solid,
    iconFont_solid,
    iconFontAwesomeLogoFull_solid,
    iconFootballBall_solid,
    iconForward_solid,
    iconFrog_solid,
    iconFrown_solid,
    iconFutbol_solid,
    iconGamepad_solid,
    iconGasPump_solid,
    iconGavel_solid,
    iconGem_solid,
    iconGenderless_solid,
    iconGift_solid,
    iconGlassMartini_solid,
    iconGlasses_solid,
    iconGlobe_solid,
    iconGolfBall_solid,
    iconGraduationCap_solid,
    iconGreaterThan_solid,
    iconGreaterThanEqual_solid,
    iconHSquare_solid,
    iconHandHolding_solid,
    iconHandHoldingHeart_solid,
    iconHandHoldingUsd_solid,
    iconHandLizard_solid,
    iconHandPaper_solid,
    iconHandPeace_solid,
    iconHandPointDown_solid,
    iconHandPointLeft_solid,
    iconHandPointRight_solid,
    iconHandPointUp_solid,
    iconHandPointer_solid,
    iconHandRock_solid,
    iconHandScissors_solid,
    iconHandSpock_solid,
    iconHands_solid,
    iconHandsHelping_solid,
    iconHandshake_solid,
    iconHashtag_solid,
    iconHdd_solid,
    iconHeading_solid,
    iconHeadphones_solid,
    iconHeart_solid,
    iconHeartbeat_solid,
    iconHelicopter_solid,
    iconHistory_solid,
    iconHockeyPuck_solid,
    iconHome_solid,
    iconHospital_solid,
    iconHospitalAlt_solid,
    iconHospitalSymbol_solid,
    iconHourglass_solid,
    iconHourglassEnd_solid,
    iconHourglassHalf_solid,
    iconHourglassStart_solid,
    iconICursor_solid,
    iconIdBadge_solid,
    iconIdCard_solid,
    iconIdCardAlt_solid,
    iconImage_solid,
    iconImages_solid,
    iconInbox_solid,
    iconIndent_solid,
    iconIndustry_solid,
    iconInfinity_solid,
    iconInfo_solid,
    iconInfoCircle_solid,
    iconItalic_solid,
    iconKey_solid,
    iconKeyboard_solid,
    iconKiwiBird_solid,
    iconLanguage_solid,
    iconLaptop_solid,
    iconLeaf_solid,
    iconLemon_solid,
    iconLessThan_solid,
    iconLessThanEqual_solid,
    iconLevelDownAlt_solid,
    iconLevelUpAlt_solid,
    iconLifeRing_solid,
    iconLightbulb_solid,
    iconLink_solid,
    iconLiraSign_solid,
    iconList_solid,
    iconListAlt_solid,
    iconListOl_solid,
    iconListUl_solid,
    iconLocationArrow_solid,
    iconLock_solid,
    iconLockOpen_solid,
    iconLongArrowAltDown_solid,
    iconLongArrowAltLeft_solid,
    iconLongArrowAltRight_solid,
    iconLongArrowAltUp_solid,
    iconLowVision_solid,
    iconMagic_solid,
    iconMagnet_solid,
    iconMale_solid,
    iconMap_solid,
    iconMapMarker_solid,
    iconMapMarkerAlt_solid,
    iconMapPin_solid,
    iconMapSigns_solid,
    iconMars_solid,
    iconMarsDouble_solid,
    iconMarsStroke_solid,
    iconMarsStrokeH_solid,
    iconMarsStrokeV_solid,
    iconMedkit_solid,
    iconMeh_solid,
    iconMemory_solid,
    iconMercury_solid,
    iconMicrochip_solid,
    iconMicrophone_solid,
    iconMicrophoneAlt_solid,
    iconMicrophoneAltSlash_solid,
    iconMicrophoneSlash_solid,
    iconMinus_solid,
    iconMinusCircle_solid,
    iconMinusSquare_solid,
    iconMobile_solid,
    iconMobileAlt_solid,
    iconMoneyBill_solid,
    iconMoneyBillAlt_solid,
    iconMoneyBillWave_solid,
    iconMoneyBillWaveAlt_solid,
    iconMoneyCheck_solid,
    iconMoneyCheckAlt_solid,
    iconMoon_solid,
    iconMotorcycle_solid,
    iconMousePointer_solid,
    iconMusic_solid,
    iconNeuter_solid,
    iconNewspaper_solid,
    iconNotEqual_solid,
    iconNotesMedical_solid,
    iconObjectGroup_solid,
    iconObjectUngroup_solid,
    iconOutdent_solid,
    iconPaintBrush_solid,
    iconPalette_solid,
    iconPallet_solid,
    iconPaperPlane_solid,
    iconPaperclip_solid,
    iconParachuteBox_solid,
    iconParagraph_solid,
    iconParking_solid,
    iconPaste_solid,
    iconPause_solid,
    iconPauseCircle_solid,
    iconPaw_solid,
    iconPenSquare_solid,
    iconPencilAlt_solid,
    iconPeopleCarry_solid,
    iconPercent_solid,
    iconPercentage_solid,
    iconPhone_solid,
    iconPhoneSlash_solid,
    iconPhoneSquare_solid,
    iconPhoneVolume_solid,
    iconPiggyBank_solid,
    iconPills_solid,
    iconPlane_solid,
    iconPlay_solid,
    iconPlayCircle_solid,
    iconPlug_solid,
    iconPlus_solid,
    iconPlusCircle_solid,
    iconPlusSquare_solid,
    iconPodcast_solid,
    iconPoo_solid,
    iconPortrait_solid,
    iconPoundSign_solid,
    iconPowerOff_solid,
    iconPrescriptionBottle_solid,
    iconPrescriptionBottleAlt_solid,
    iconPrint_solid,
    iconProcedures_solid,
    iconProjectDiagram_solid,
    iconPuzzlePiece_solid,
    iconQrcode_solid,
    iconQuestion_solid,
    iconQuestionCircle_solid,
    iconQuidditch_solid,
    iconQuoteLeft_solid,
    iconQuoteRight_solid,
    iconRandom_solid,
    iconReceipt_solid,
    iconRecycle_solid,
    iconRedo_solid,
    iconRedoAlt_solid,
    iconRegistered_solid,
    iconReply_solid,
    iconReplyAll_solid,
    iconRetweet_solid,
    iconRibbon_solid,
    iconRoad_solid,
    iconRobot_solid,
    iconRocket_solid,
    iconRss_solid,
    iconRssSquare_solid,
    iconRubleSign_solid,
    iconRuler_solid,
    iconRulerCombined_solid,
    iconRulerHorizontal_solid,
    iconRulerVertical_solid,
    iconRupeeSign_solid,
    iconSave_solid,
    iconSchool_solid,
    iconScrewdriver_solid,
    iconSearch_solid,
    iconSearchMinus_solid,
    iconSearchPlus_solid,
    iconSeedling_solid,
    iconServer_solid,
    iconShare_solid,
    iconShareAlt_solid,
    iconShareAltSquare_solid,
    iconShareSquare_solid,
    iconShekelSign_solid,
    iconShieldAlt_solid,
    iconShip_solid,
    iconShippingFast_solid,
    iconShoePrints_solid,
    iconShoppingBag_solid,
    iconShoppingBasket_solid,
    iconShoppingCart_solid,
    iconShower_solid,
    iconSign_solid,
    iconSignInAlt_solid,
    iconSignLanguage_solid,
    iconSignOutAlt_solid,
    iconSignal_solid,
    iconSitemap_solid,
    iconSkull_solid,
    iconSlidersH_solid,
    iconSmile_solid,
    iconSmoking_solid,
    iconSmokingBan_solid,
    iconSnowflake_solid,
    iconSort_solid,
    iconSortAlphaDown_solid,
    iconSortAlphaUp_solid,
    iconSortAmountDown_solid,
    iconSortAmountUp_solid,
    iconSortDown_solid,
    iconSortNumericDown_solid,
    iconSortNumericUp_solid,
    iconSortUp_solid,
    iconSpaceShuttle_solid,
    iconSpinner_solid,
    iconSquare_solid,
    iconSquareFull_solid,
    iconStar_solid,
    iconStarHalf_solid,
    iconStepBackward_solid,
    iconStepForward_solid,
    iconStethoscope_solid,
    iconStickyNote_solid,
    iconStop_solid,
    iconStopCircle_solid,
    iconStopwatch_solid,
    iconStore_solid,
    iconStoreAlt_solid,
    iconStream_solid,
    iconStreetView_solid,
    iconStrikethrough_solid,
    iconStroopwafel_solid,
    iconSubscript_solid,
    iconSubway_solid,
    iconSuitcase_solid,
    iconSun_solid,
    iconSuperscript_solid,
    iconSync_solid,
    iconSyncAlt_solid,
    iconSyringe_solid,
    iconTable_solid,
    iconTableTennis_solid,
    iconTablet_solid,
    iconTabletAlt_solid,
    iconTablets_solid,
    iconTachometerAlt_solid,
    iconTag_solid,
    iconTags_solid,
    iconTape_solid,
    iconTasks_solid,
    iconTaxi_solid,
    iconTerminal_solid,
    iconTextHeight_solid,
    iconTextWidth_solid,
    iconTh_solid,
    iconThLarge_solid,
    iconThList_solid,
    iconThermometer_solid,
    iconThermometerEmpty_solid,
    iconThermometerFull_solid,
    iconThermometerHalf_solid,
    iconThermometerQuarter_solid,
    iconThermometerThreeQuarters_solid,
    iconThumbsDown_solid,
    iconThumbsUp_solid,
    iconThumbtack_solid,
    iconTicketAlt_solid,
    iconTimes_solid,
    iconTimesCircle_solid,
    iconTint_solid,
    iconToggleOff_solid,
    iconToggleOn_solid,
    iconToolbox_solid,
    iconTrademark_solid,
    iconTrain_solid,
    iconTransgender_solid,
    iconTransgenderAlt_solid,
    iconTrash_solid,
    iconTrashAlt_solid,
    iconTree_solid,
    iconTrophy_solid,
    iconTruck_solid,
    iconTruckLoading_solid,
    iconTruckMoving_solid,
    iconTshirt_solid,
    iconTty_solid,
    iconTv_solid,
    iconUmbrella_solid,
    iconUnderline_solid,
    iconUndo_solid,
    iconUndoAlt_solid,
    iconUniversalAccess_solid,
    iconUniversity_solid,
    iconUnlink_solid,
    iconUnlock_solid,
    iconUnlockAlt_solid,
    iconUpload_solid,
    iconUser_solid,
    iconUserAlt_solid,
    iconUserAltSlash_solid,
    iconUserAstronaut_solid,
    iconUserCheck_solid,
    iconUserCircle_solid,
    iconUserClock_solid,
    iconUserCog_solid,
    iconUserEdit_solid,
    iconUserFriends_solid,
    iconUserGraduate_solid,
    iconUserLock_solid,
    iconUserMd_solid,
    iconUserMinus_solid,
    iconUserNinja_solid,
    iconUserPlus_solid,
    iconUserSecret_solid,
    iconUserShield_solid,
    iconUserSlash_solid,
    iconUserTag_solid,
    iconUserTie_solid,
    iconUserTimes_solid,
    iconUsers_solid,
    iconUsersCog_solid,
    iconUtensilSpoon_solid,
    iconUtensils_solid,
    iconVenus_solid,
    iconVenusDouble_solid,
    iconVenusMars_solid,
    iconVial_solid,
    iconVials_solid,
    iconVideo_solid,
    iconVideoSlash_solid,
    iconVolleyballBall_solid,
    iconVolumeDown_solid,
    iconVolumeOff_solid,
    iconVolumeUp_solid,
    iconWalking_solid,
    iconWallet_solid,
    iconWarehouse_solid,
    iconWeight_solid,
    iconWheelchair_solid,
    iconWifi_solid,
    iconWindowClose_solid,
    iconWindowMaximize_solid,
    iconWindowMinimize_solid,
    iconWindowRestore_solid,
    iconWineGlass_solid,
    iconWonSign_solid,
    iconWrench_solid,
    iconXRay_solid,
    iconYenSign_solid,
}
export {
    iconAddressBook_regular,
    iconAddressCard_regular,
    iconArrowAltCircleDown_regular,
    iconArrowAltCircleLeft_regular,
    iconArrowAltCircleRight_regular,
    iconArrowAltCircleUp_regular,
    iconBell_regular,
    iconBellSlash_regular,
    iconBookmark_regular,
    iconBuilding_regular,
    iconCalendar_regular,
    iconCalendarAlt_regular,
    iconCalendarCheck_regular,
    iconCalendarMinus_regular,
    iconCalendarPlus_regular,
    iconCalendarTimes_regular,
    iconCaretSquareDown_regular,
    iconCaretSquareLeft_regular,
    iconCaretSquareRight_regular,
    iconCaretSquareUp_regular,
    iconChartBar_regular,
    iconCheckCircle_regular,
    iconCheckSquare_regular,
    iconCircle_regular,
    iconClipboard_regular,
    iconClock_regular,
    iconClone_regular,
    iconClosedCaptioning_regular,
    iconComment_regular,
    iconCommentAlt_regular,
    iconCommentDots_regular,
    iconComments_regular,
    iconCompass_regular,
    iconCopy_regular,
    iconCopyright_regular,
    iconCreditCard_regular,
    iconDotCircle_regular,
    iconEdit_regular,
    iconEnvelope_regular,
    iconEnvelopeOpen_regular,
    iconEye_regular,
    iconEyeSlash_regular,
    iconFile_regular,
    iconFileAlt_regular,
    iconFileArchive_regular,
    iconFileAudio_regular,
    iconFileCode_regular,
    iconFileExcel_regular,
    iconFileImage_regular,
    iconFilePdf_regular,
    iconFilePowerpoint_regular,
    iconFileVideo_regular,
    iconFileWord_regular,
    iconFlag_regular,
    iconFolder_regular,
    iconFolderOpen_regular,
    iconFontAwesomeLogoFull_regular,
    iconFrown_regular,
    iconFutbol_regular,
    iconGem_regular,
    iconHandLizard_regular,
    iconHandPaper_regular,
    iconHandPeace_regular,
    iconHandPointDown_regular,
    iconHandPointLeft_regular,
    iconHandPointRight_regular,
    iconHandPointUp_regular,
    iconHandPointer_regular,
    iconHandRock_regular,
    iconHandScissors_regular,
    iconHandSpock_regular,
    iconHandshake_regular,
    iconHdd_regular,
    iconHeart_regular,
    iconHospital_regular,
    iconHourglass_regular,
    iconIdBadge_regular,
    iconIdCard_regular,
    iconImage_regular,
    iconImages_regular,
    iconKeyboard_regular,
    iconLemon_regular,
    iconLifeRing_regular,
    iconLightbulb_regular,
    iconListAlt_regular,
    iconMap_regular,
    iconMeh_regular,
    iconMinusSquare_regular,
    iconMoneyBillAlt_regular,
    iconMoon_regular,
    iconNewspaper_regular,
    iconObjectGroup_regular,
    iconObjectUngroup_regular,
    iconPaperPlane_regular,
    iconPauseCircle_regular,
    iconPlayCircle_regular,
    iconPlusSquare_regular,
    iconQuestionCircle_regular,
    iconRegistered_regular,
    iconSave_regular,
    iconShareSquare_regular,
    iconSmile_regular,
    iconSnowflake_regular,
    iconSquare_regular,
    iconStar_regular,
    iconStarHalf_regular,
    iconStickyNote_regular,
    iconStopCircle_regular,
    iconSun_regular,
    iconThumbsDown_regular,
    iconThumbsUp_regular,
    iconTimesCircle_regular,
    iconTrashAlt_regular,
    iconUser_regular,
    iconUserCircle_regular,
    iconWindowClose_regular,
    iconWindowMaximize_regular,
    iconWindowMinimize_regular,
    iconWindowRestore_regular,
}

import {
    fa500px as icon500px_brand,
    faAccessibleIcon as iconAccessibleIcon_brand,
    faAccusoft as iconAccusoft_brand,
    faAdn as iconAdn_brand,
    faAdversal as iconAdversal_brand,
    faAffiliatetheme as iconAffiliatetheme_brand,
    faAlgolia as iconAlgolia_brand,
    faAmazon as iconAmazon_brand,
    faAmazonPay as iconAmazonPay_brand,
    faAmilia as iconAmilia_brand,
    faAndroid as iconAndroid_brand,
    faAngellist as iconAngellist_brand,
    faAngrycreative as iconAngrycreative_brand,
    faAngular as iconAngular_brand,
    faAppStore as iconAppStore_brand,
    faAppStoreIos as iconAppStoreIos_brand,
    faApper as iconApper_brand,
    faApple as iconApple_brand,
    faApplePay as iconApplePay_brand,
    faAsymmetrik as iconAsymmetrik_brand,
    faAudible as iconAudible_brand,
    faAutoprefixer as iconAutoprefixer_brand,
    faAvianex as iconAvianex_brand,
    faAviato as iconAviato_brand,
    faAws as iconAws_brand,
    faBandcamp as iconBandcamp_brand,
    faBehance as iconBehance_brand,
    faBehanceSquare as iconBehanceSquare_brand,
    faBimobject as iconBimobject_brand,
    faBitbucket as iconBitbucket_brand,
    faBitcoin as iconBitcoin_brand,
    faBity as iconBity_brand,
    faBlackTie as iconBlackTie_brand,
    faBlackberry as iconBlackberry_brand,
    faBlogger as iconBlogger_brand,
    faBloggerB as iconBloggerB_brand,
    faBluetooth as iconBluetooth_brand,
    faBluetoothB as iconBluetoothB_brand,
    faBtc as iconBtc_brand,
    faBuromobelexperte as iconBuromobelexperte_brand,
    faBuysellads as iconBuysellads_brand,
    faCcAmazonPay as iconCcAmazonPay_brand,
    faCcAmex as iconCcAmex_brand,
    faCcApplePay as iconCcApplePay_brand,
    faCcDinersClub as iconCcDinersClub_brand,
    faCcDiscover as iconCcDiscover_brand,
    faCcJcb as iconCcJcb_brand,
    faCcMastercard as iconCcMastercard_brand,
    faCcPaypal as iconCcPaypal_brand,
    faCcStripe as iconCcStripe_brand,
    faCcVisa as iconCcVisa_brand,
    faCentercode as iconCentercode_brand,
    faChrome as iconChrome_brand,
    faCloudscale as iconCloudscale_brand,
    faCloudsmith as iconCloudsmith_brand,
    faCloudversify as iconCloudversify_brand,
    faCodepen as iconCodepen_brand,
    faCodiepie as iconCodiepie_brand,
    faConnectdevelop as iconConnectdevelop_brand,
    faContao as iconContao_brand,
    faCpanel as iconCpanel_brand,
    faCreativeCommons as iconCreativeCommons_brand,
    faCreativeCommonsBy as iconCreativeCommonsBy_brand,
    faCreativeCommonsNc as iconCreativeCommonsNc_brand,
    faCreativeCommonsNcEu as iconCreativeCommonsNcEu_brand,
    faCreativeCommonsNcJp as iconCreativeCommonsNcJp_brand,
    faCreativeCommonsNd as iconCreativeCommonsNd_brand,
    faCreativeCommonsPd as iconCreativeCommonsPd_brand,
    faCreativeCommonsPdAlt as iconCreativeCommonsPdAlt_brand,
    faCreativeCommonsRemix as iconCreativeCommonsRemix_brand,
    faCreativeCommonsSa as iconCreativeCommonsSa_brand,
    faCreativeCommonsSampling as iconCreativeCommonsSampling_brand,
    faCreativeCommonsSamplingPlus as iconCreativeCommonsSamplingPlus_brand,
    faCreativeCommonsShare as iconCreativeCommonsShare_brand,
    faCss3 as iconCss3_brand,
    faCss3Alt as iconCss3Alt_brand,
    faCuttlefish as iconCuttlefish_brand,
    faDAndD as iconDAndD_brand,
    faDashcube as iconDashcube_brand,
    faDelicious as iconDelicious_brand,
    faDeploydog as iconDeploydog_brand,
    faDeskpro as iconDeskpro_brand,
    faDeviantart as iconDeviantart_brand,
    faDigg as iconDigg_brand,
    faDigitalOcean as iconDigitalOcean_brand,
    faDiscord as iconDiscord_brand,
    faDiscourse as iconDiscourse_brand,
    faDochub as iconDochub_brand,
    faDocker as iconDocker_brand,
    faDraft2digital as iconDraft2digital_brand,
    faDribbble as iconDribbble_brand,
    faDribbbleSquare as iconDribbbleSquare_brand,
    faDropbox as iconDropbox_brand,
    faDrupal as iconDrupal_brand,
    faDyalog as iconDyalog_brand,
    faEarlybirds as iconEarlybirds_brand,
    faEbay as iconEbay_brand,
    faEdge as iconEdge_brand,
    faElementor as iconElementor_brand,
    faEmber as iconEmber_brand,
    faEmpire as iconEmpire_brand,
    faEnvira as iconEnvira_brand,
    faErlang as iconErlang_brand,
    faEthereum as iconEthereum_brand,
    faEtsy as iconEtsy_brand,
    faExpeditedssl as iconExpeditedssl_brand,
    faFacebook as iconFacebook_brand,
    faFacebookF as iconFacebookF_brand,
    faFacebookMessenger as iconFacebookMessenger_brand,
    faFacebookSquare as iconFacebookSquare_brand,
    faFirefox as iconFirefox_brand,
    faFirstOrder as iconFirstOrder_brand,
    faFirstOrderAlt as iconFirstOrderAlt_brand,
    faFirstdraft as iconFirstdraft_brand,
    faFlickr as iconFlickr_brand,
    faFlipboard as iconFlipboard_brand,
    faFly as iconFly_brand,
    faFontAwesome as iconFontAwesome_brand,
    faFontAwesomeAlt as iconFontAwesomeAlt_brand,
    faFontAwesomeFlag as iconFontAwesomeFlag_brand,
    faFontAwesomeLogoFull as iconFontAwesomeLogoFull_brand,
    faFonticons as iconFonticons_brand,
    faFonticonsFi as iconFonticonsFi_brand,
    faFortAwesome as iconFortAwesome_brand,
    faFortAwesomeAlt as iconFortAwesomeAlt_brand,
    faForumbee as iconForumbee_brand,
    faFoursquare as iconFoursquare_brand,
    faFreeCodeCamp as iconFreeCodeCamp_brand,
    faFreebsd as iconFreebsd_brand,
    faFulcrum as iconFulcrum_brand,
    faGalacticRepublic as iconGalacticRepublic_brand,
    faGalacticSenate as iconGalacticSenate_brand,
    faGetPocket as iconGetPocket_brand,
    faGg as iconGg_brand,
    faGgCircle as iconGgCircle_brand,
    faGit as iconGit_brand,
    faGitSquare as iconGitSquare_brand,
    faGithub as iconGithub_brand,
    faGithubAlt as iconGithubAlt_brand,
    faGithubSquare as iconGithubSquare_brand,
    faGitkraken as iconGitkraken_brand,
    faGitlab as iconGitlab_brand,
    faGitter as iconGitter_brand,
    faGlide as iconGlide_brand,
    faGlideG as iconGlideG_brand,
    faGofore as iconGofore_brand,
    faGoodreads as iconGoodreads_brand,
    faGoodreadsG as iconGoodreadsG_brand,
    faGoogle as iconGoogle_brand,
    faGoogleDrive as iconGoogleDrive_brand,
    faGooglePlay as iconGooglePlay_brand,
    faGooglePlus as iconGooglePlus_brand,
    faGooglePlusG as iconGooglePlusG_brand,
    faGooglePlusSquare as iconGooglePlusSquare_brand,
    faGoogleWallet as iconGoogleWallet_brand,
    faGratipay as iconGratipay_brand,
    faGrav as iconGrav_brand,
    faGripfire as iconGripfire_brand,
    faGrunt as iconGrunt_brand,
    faGulp as iconGulp_brand,
    faHackerNews as iconHackerNews_brand,
    faHackerNewsSquare as iconHackerNewsSquare_brand,
    faHips as iconHips_brand,
    faHireAHelper as iconHireAHelper_brand,
    faHooli as iconHooli_brand,
    faHotjar as iconHotjar_brand,
    faHouzz as iconHouzz_brand,
    faHtml5 as iconHtml5_brand,
    faHubspot as iconHubspot_brand,
    faImdb as iconImdb_brand,
    faInstagram as iconInstagram_brand,
    faInternetExplorer as iconInternetExplorer_brand,
    faIoxhost as iconIoxhost_brand,
    faItunes as iconItunes_brand,
    faItunesNote as iconItunesNote_brand,
    faJava as iconJava_brand,
    faJediOrder as iconJediOrder_brand,
    faJenkins as iconJenkins_brand,
    faJoget as iconJoget_brand,
    faJoomla as iconJoomla_brand,
    faJs as iconJs_brand,
    faJsSquare as iconJsSquare_brand,
    faJsfiddle as iconJsfiddle_brand,
    faKeybase as iconKeybase_brand,
    faKeycdn as iconKeycdn_brand,
    faKickstarter as iconKickstarter_brand,
    faKickstarterK as iconKickstarterK_brand,
    faKorvue as iconKorvue_brand,
    faLaravel as iconLaravel_brand,
    faLastfm as iconLastfm_brand,
    faLastfmSquare as iconLastfmSquare_brand,
    faLeanpub as iconLeanpub_brand,
    faLess as iconLess_brand,
    faLine as iconLine_brand,
    faLinkedin as iconLinkedin_brand,
    faLinkedinIn as iconLinkedinIn_brand,
    faLinode as iconLinode_brand,
    faLinux as iconLinux_brand,
    faLyft as iconLyft_brand,
    faMagento as iconMagento_brand,
    faMandalorian as iconMandalorian_brand,
    faMastodon as iconMastodon_brand,
    faMaxcdn as iconMaxcdn_brand,
    faMedapps as iconMedapps_brand,
    faMedium as iconMedium_brand,
    faMediumM as iconMediumM_brand,
    faMedrt as iconMedrt_brand,
    faMeetup as iconMeetup_brand,
    faMicrosoft as iconMicrosoft_brand,
    faMix as iconMix_brand,
    faMixcloud as iconMixcloud_brand,
    faMizuni as iconMizuni_brand,
    faModx as iconModx_brand,
    faMonero as iconMonero_brand,
    faNapster as iconNapster_brand,
    faNintendoSwitch as iconNintendoSwitch_brand,
    faNode as iconNode_brand,
    faNodeJs as iconNodeJs_brand,
    faNpm as iconNpm_brand,
    faNs8 as iconNs8_brand,
    faNutritionix as iconNutritionix_brand,
    faOdnoklassniki as iconOdnoklassniki_brand,
    faOdnoklassnikiSquare as iconOdnoklassnikiSquare_brand,
    faOldRepublic as iconOldRepublic_brand,
    faOpencart as iconOpencart_brand,
    faOpenid as iconOpenid_brand,
    faOpera as iconOpera_brand,
    faOptinMonster as iconOptinMonster_brand,
    faOsi as iconOsi_brand,
    faPage4 as iconPage4_brand,
    faPagelines as iconPagelines_brand,
    faPalfed as iconPalfed_brand,
    faPatreon as iconPatreon_brand,
    faPaypal as iconPaypal_brand,
    faPeriscope as iconPeriscope_brand,
    faPhabricator as iconPhabricator_brand,
    faPhoenixFramework as iconPhoenixFramework_brand,
    faPhoenixSquadron as iconPhoenixSquadron_brand,
    faPhp as iconPhp_brand,
    faPiedPiper as iconPiedPiper_brand,
    faPiedPiperAlt as iconPiedPiperAlt_brand,
    faPiedPiperHat as iconPiedPiperHat_brand,
    faPiedPiperPp as iconPiedPiperPp_brand,
    faPinterest as iconPinterest_brand,
    faPinterestP as iconPinterestP_brand,
    faPinterestSquare as iconPinterestSquare_brand,
    faPlaystation as iconPlaystation_brand,
    faProductHunt as iconProductHunt_brand,
    faPushed as iconPushed_brand,
    faPython as iconPython_brand,
    faQq as iconQq_brand,
    faQuinscape as iconQuinscape_brand,
    faQuora as iconQuora_brand,
    faRProject as iconRProject_brand,
    faRavelry as iconRavelry_brand,
    faReact as iconReact_brand,
    faReadme as iconReadme_brand,
    faRebel as iconRebel_brand,
    faRedRiver as iconRedRiver_brand,
    faReddit as iconReddit_brand,
    faRedditAlien as iconRedditAlien_brand,
    faRedditSquare as iconRedditSquare_brand,
    faRendact as iconRendact_brand,
    faRenren as iconRenren_brand,
    faReplyd as iconReplyd_brand,
    faResearchgate as iconResearchgate_brand,
    faResolving as iconResolving_brand,
    faRocketchat as iconRocketchat_brand,
    faRockrms as iconRockrms_brand,
    faSafari as iconSafari_brand,
    faSass as iconSass_brand,
    faSchlix as iconSchlix_brand,
    faScribd as iconScribd_brand,
    faSearchengin as iconSearchengin_brand,
    faSellcast as iconSellcast_brand,
    faSellsy as iconSellsy_brand,
    faServicestack as iconServicestack_brand,
    faShirtsinbulk as iconShirtsinbulk_brand,
    faSimplybuilt as iconSimplybuilt_brand,
    faSistrix as iconSistrix_brand,
    faSith as iconSith_brand,
    faSkyatlas as iconSkyatlas_brand,
    faSkype as iconSkype_brand,
    faSlack as iconSlack_brand,
    faSlackHash as iconSlackHash_brand,
    faSlideshare as iconSlideshare_brand,
    faSnapchat as iconSnapchat_brand,
    faSnapchatGhost as iconSnapchatGhost_brand,
    faSnapchatSquare as iconSnapchatSquare_brand,
    faSoundcloud as iconSoundcloud_brand,
    faSpeakap as iconSpeakap_brand,
    faSpotify as iconSpotify_brand,
    faStackExchange as iconStackExchange_brand,
    faStackOverflow as iconStackOverflow_brand,
    faStaylinked as iconStaylinked_brand,
    faSteam as iconSteam_brand,
    faSteamSquare as iconSteamSquare_brand,
    faSteamSymbol as iconSteamSymbol_brand,
    faStickerMule as iconStickerMule_brand,
    faStrava as iconStrava_brand,
    faStripe as iconStripe_brand,
    faStripeS as iconStripeS_brand,
    faStudiovinari as iconStudiovinari_brand,
    faStumbleupon as iconStumbleupon_brand,
    faStumbleuponCircle as iconStumbleuponCircle_brand,
    faSuperpowers as iconSuperpowers_brand,
    faSupple as iconSupple_brand,
    faTeamspeak as iconTeamspeak_brand,
    faTelegram as iconTelegram_brand,
    faTelegramPlane as iconTelegramPlane_brand,
    faTencentWeibo as iconTencentWeibo_brand,
    faThemeisle as iconThemeisle_brand,
    faTradeFederation as iconTradeFederation_brand,
    faTrello as iconTrello_brand,
    faTripadvisor as iconTripadvisor_brand,
    faTumblr as iconTumblr_brand,
    faTumblrSquare as iconTumblrSquare_brand,
    faTwitch as iconTwitch_brand,
    faTwitter as iconTwitter_brand,
    faTwitterSquare as iconTwitterSquare_brand,
    faTypo3 as iconTypo3_brand,
    faUber as iconUber_brand,
    faUikit as iconUikit_brand,
    faUniregistry as iconUniregistry_brand,
    faUntappd as iconUntappd_brand,
    faUsb as iconUsb_brand,
    faUssunnah as iconUssunnah_brand,
    faVaadin as iconVaadin_brand,
    faViacoin as iconViacoin_brand,
    faViadeo as iconViadeo_brand,
    faViadeoSquare as iconViadeoSquare_brand,
    faViber as iconViber_brand,
    faVimeo as iconVimeo_brand,
    faVimeoSquare as iconVimeoSquare_brand,
    faVimeoV as iconVimeoV_brand,
    faVine as iconVine_brand,
    faVk as iconVk_brand,
    faVnv as iconVnv_brand,
    faVuejs as iconVuejs_brand,
    faWeibo as iconWeibo_brand,
    faWeixin as iconWeixin_brand,
    faWhatsapp as iconWhatsapp_brand,
    faWhatsappSquare as iconWhatsappSquare_brand,
    faWhmcs as iconWhmcs_brand,
    faWikipediaW as iconWikipediaW_brand,
    faWindows as iconWindows_brand,
    faWolfPackBattalion as iconWolfPackBattalion_brand,
    faWordpress as iconWordpress_brand,
    faWordpressSimple as iconWordpressSimple_brand,
    faWpbeginner as iconWpbeginner_brand,
    faWpexplorer as iconWpexplorer_brand,
    faWpforms as iconWpforms_brand,
    faXbox as iconXbox_brand,
    faXing as iconXing_brand,
    faXingSquare as iconXingSquare_brand,
    faYCombinator as iconYCombinator_brand,
    faYahoo as iconYahoo_brand,
    faYandex as iconYandex_brand,
    faYandexInternational as iconYandexInternational_brand,
    faYelp as iconYelp_brand,
    faYoast as iconYoast_brand,
    faYoutube as iconYoutube_brand,
    faYoutubeSquare as iconYoutubeSquare_brand,
} from '@fortawesome/free-brands-svg-icons';
export {
    icon500px_brand,
    iconAccessibleIcon_brand,
    iconAccusoft_brand,
    iconAdn_brand,
    iconAdversal_brand,
    iconAffiliatetheme_brand,
    iconAlgolia_brand,
    iconAmazon_brand,
    iconAmazonPay_brand,
    iconAmilia_brand,
    iconAndroid_brand,
    iconAngellist_brand,
    iconAngrycreative_brand,
    iconAngular_brand,
    iconAppStore_brand,
    iconAppStoreIos_brand,
    iconApper_brand,
    iconApple_brand,
    iconApplePay_brand,
    iconAsymmetrik_brand,
    iconAudible_brand,
    iconAutoprefixer_brand,
    iconAvianex_brand,
    iconAviato_brand,
    iconAws_brand,
    iconBandcamp_brand,
    iconBehance_brand,
    iconBehanceSquare_brand,
    iconBimobject_brand,
    iconBitbucket_brand,
    iconBitcoin_brand,
    iconBity_brand,
    iconBlackTie_brand,
    iconBlackberry_brand,
    iconBlogger_brand,
    iconBloggerB_brand,
    iconBluetooth_brand,
    iconBluetoothB_brand,
    iconBtc_brand,
    iconBuromobelexperte_brand,
    iconBuysellads_brand,
    iconCcAmazonPay_brand,
    iconCcAmex_brand,
    iconCcApplePay_brand,
    iconCcDinersClub_brand,
    iconCcDiscover_brand,
    iconCcJcb_brand,
    iconCcMastercard_brand,
    iconCcPaypal_brand,
    iconCcStripe_brand,
    iconCcVisa_brand,
    iconCentercode_brand,
    iconChrome_brand,
    iconCloudscale_brand,
    iconCloudsmith_brand,
    iconCloudversify_brand,
    iconCodepen_brand,
    iconCodiepie_brand,
    iconConnectdevelop_brand,
    iconContao_brand,
    iconCpanel_brand,
    iconCreativeCommons_brand,
    iconCreativeCommonsBy_brand,
    iconCreativeCommonsNc_brand,
    iconCreativeCommonsNcEu_brand,
    iconCreativeCommonsNcJp_brand,
    iconCreativeCommonsNd_brand,
    iconCreativeCommonsPd_brand,
    iconCreativeCommonsPdAlt_brand,
    iconCreativeCommonsRemix_brand,
    iconCreativeCommonsSa_brand,
    iconCreativeCommonsSampling_brand,
    iconCreativeCommonsSamplingPlus_brand,
    iconCreativeCommonsShare_brand,
    iconCss3_brand,
    iconCss3Alt_brand,
    iconCuttlefish_brand,
    iconDAndD_brand,
    iconDashcube_brand,
    iconDelicious_brand,
    iconDeploydog_brand,
    iconDeskpro_brand,
    iconDeviantart_brand,
    iconDigg_brand,
    iconDigitalOcean_brand,
    iconDiscord_brand,
    iconDiscourse_brand,
    iconDochub_brand,
    iconDocker_brand,
    iconDraft2digital_brand,
    iconDribbble_brand,
    iconDribbbleSquare_brand,
    iconDropbox_brand,
    iconDrupal_brand,
    iconDyalog_brand,
    iconEarlybirds_brand,
    iconEbay_brand,
    iconEdge_brand,
    iconElementor_brand,
    iconEmber_brand,
    iconEmpire_brand,
    iconEnvira_brand,
    iconErlang_brand,
    iconEthereum_brand,
    iconEtsy_brand,
    iconExpeditedssl_brand,
    iconFacebook_brand,
    iconFacebookF_brand,
    iconFacebookMessenger_brand,
    iconFacebookSquare_brand,
    iconFirefox_brand,
    iconFirstOrder_brand,
    iconFirstOrderAlt_brand,
    iconFirstdraft_brand,
    iconFlickr_brand,
    iconFlipboard_brand,
    iconFly_brand,
    iconFontAwesome_brand,
    iconFontAwesomeAlt_brand,
    iconFontAwesomeFlag_brand,
    iconFontAwesomeLogoFull_brand,
    iconFonticons_brand,
    iconFonticonsFi_brand,
    iconFortAwesome_brand,
    iconFortAwesomeAlt_brand,
    iconForumbee_brand,
    iconFoursquare_brand,
    iconFreeCodeCamp_brand,
    iconFreebsd_brand,
    iconFulcrum_brand,
    iconGalacticRepublic_brand,
    iconGalacticSenate_brand,
    iconGetPocket_brand,
    iconGg_brand,
    iconGgCircle_brand,
    iconGit_brand,
    iconGitSquare_brand,
    iconGithub_brand,
    iconGithubAlt_brand,
    iconGithubSquare_brand,
    iconGitkraken_brand,
    iconGitlab_brand,
    iconGitter_brand,
    iconGlide_brand,
    iconGlideG_brand,
    iconGofore_brand,
    iconGoodreads_brand,
    iconGoodreadsG_brand,
    iconGoogle_brand,
    iconGoogleDrive_brand,
    iconGooglePlay_brand,
    iconGooglePlus_brand,
    iconGooglePlusG_brand,
    iconGooglePlusSquare_brand,
    iconGoogleWallet_brand,
    iconGratipay_brand,
    iconGrav_brand,
    iconGripfire_brand,
    iconGrunt_brand,
    iconGulp_brand,
    iconHackerNews_brand,
    iconHackerNewsSquare_brand,
    iconHips_brand,
    iconHireAHelper_brand,
    iconHooli_brand,
    iconHotjar_brand,
    iconHouzz_brand,
    iconHtml5_brand,
    iconHubspot_brand,
    iconImdb_brand,
    iconInstagram_brand,
    iconInternetExplorer_brand,
    iconIoxhost_brand,
    iconItunes_brand,
    iconItunesNote_brand,
    iconJava_brand,
    iconJediOrder_brand,
    iconJenkins_brand,
    iconJoget_brand,
    iconJoomla_brand,
    iconJs_brand,
    iconJsSquare_brand,
    iconJsfiddle_brand,
    iconKeybase_brand,
    iconKeycdn_brand,
    iconKickstarter_brand,
    iconKickstarterK_brand,
    iconKorvue_brand,
    iconLaravel_brand,
    iconLastfm_brand,
    iconLastfmSquare_brand,
    iconLeanpub_brand,
    iconLess_brand,
    iconLine_brand,
    iconLinkedin_brand,
    iconLinkedinIn_brand,
    iconLinode_brand,
    iconLinux_brand,
    iconLyft_brand,
    iconMagento_brand,
    iconMandalorian_brand,
    iconMastodon_brand,
    iconMaxcdn_brand,
    iconMedapps_brand,
    iconMedium_brand,
    iconMediumM_brand,
    iconMedrt_brand,
    iconMeetup_brand,
    iconMicrosoft_brand,
    iconMix_brand,
    iconMixcloud_brand,
    iconMizuni_brand,
    iconModx_brand,
    iconMonero_brand,
    iconNapster_brand,
    iconNintendoSwitch_brand,
    iconNode_brand,
    iconNodeJs_brand,
    iconNpm_brand,
    iconNs8_brand,
    iconNutritionix_brand,
    iconOdnoklassniki_brand,
    iconOdnoklassnikiSquare_brand,
    iconOldRepublic_brand,
    iconOpencart_brand,
    iconOpenid_brand,
    iconOpera_brand,
    iconOptinMonster_brand,
    iconOsi_brand,
    iconPage4_brand,
    iconPagelines_brand,
    iconPalfed_brand,
    iconPatreon_brand,
    iconPaypal_brand,
    iconPeriscope_brand,
    iconPhabricator_brand,
    iconPhoenixFramework_brand,
    iconPhoenixSquadron_brand,
    iconPhp_brand,
    iconPiedPiper_brand,
    iconPiedPiperAlt_brand,
    iconPiedPiperHat_brand,
    iconPiedPiperPp_brand,
    iconPinterest_brand,
    iconPinterestP_brand,
    iconPinterestSquare_brand,
    iconPlaystation_brand,
    iconProductHunt_brand,
    iconPushed_brand,
    iconPython_brand,
    iconQq_brand,
    iconQuinscape_brand,
    iconQuora_brand,
    iconRProject_brand,
    iconRavelry_brand,
    iconReact_brand,
    iconReadme_brand,
    iconRebel_brand,
    iconRedRiver_brand,
    iconReddit_brand,
    iconRedditAlien_brand,
    iconRedditSquare_brand,
    iconRendact_brand,
    iconRenren_brand,
    iconReplyd_brand,
    iconResearchgate_brand,
    iconResolving_brand,
    iconRocketchat_brand,
    iconRockrms_brand,
    iconSafari_brand,
    iconSass_brand,
    iconSchlix_brand,
    iconScribd_brand,
    iconSearchengin_brand,
    iconSellcast_brand,
    iconSellsy_brand,
    iconServicestack_brand,
    iconShirtsinbulk_brand,
    iconSimplybuilt_brand,
    iconSistrix_brand,
    iconSith_brand,
    iconSkyatlas_brand,
    iconSkype_brand,
    iconSlack_brand,
    iconSlackHash_brand,
    iconSlideshare_brand,
    iconSnapchat_brand,
    iconSnapchatGhost_brand,
    iconSnapchatSquare_brand,
    iconSoundcloud_brand,
    iconSpeakap_brand,
    iconSpotify_brand,
    iconStackExchange_brand,
    iconStackOverflow_brand,
    iconStaylinked_brand,
    iconSteam_brand,
    iconSteamSquare_brand,
    iconSteamSymbol_brand,
    iconStickerMule_brand,
    iconStrava_brand,
    iconStripe_brand,
    iconStripeS_brand,
    iconStudiovinari_brand,
    iconStumbleupon_brand,
    iconStumbleuponCircle_brand,
    iconSuperpowers_brand,
    iconSupple_brand,
    iconTeamspeak_brand,
    iconTelegram_brand,
    iconTelegramPlane_brand,
    iconTencentWeibo_brand,
    iconThemeisle_brand,
    iconTradeFederation_brand,
    iconTrello_brand,
    iconTripadvisor_brand,
    iconTumblr_brand,
    iconTumblrSquare_brand,
    iconTwitch_brand,
    iconTwitter_brand,
    iconTwitterSquare_brand,
    iconTypo3_brand,
    iconUber_brand,
    iconUikit_brand,
    iconUniregistry_brand,
    iconUntappd_brand,
    iconUsb_brand,
    iconUssunnah_brand,
    iconVaadin_brand,
    iconViacoin_brand,
    iconViadeo_brand,
    iconViadeoSquare_brand,
    iconViber_brand,
    iconVimeo_brand,
    iconVimeoSquare_brand,
    iconVimeoV_brand,
    iconVine_brand,
    iconVk_brand,
    iconVnv_brand,
    iconVuejs_brand,
    iconWeibo_brand,
    iconWeixin_brand,
    iconWhatsapp_brand,
    iconWhatsappSquare_brand,
    iconWhmcs_brand,
    iconWikipediaW_brand,
    iconWindows_brand,
    iconWolfPackBattalion_brand,
    iconWordpress_brand,
    iconWordpressSimple_brand,
    iconWpbeginner_brand,
    iconWpexplorer_brand,
    iconWpforms_brand,
    iconXbox_brand,
    iconXing_brand,
    iconXingSquare_brand,
    iconYCombinator_brand,
    iconYahoo_brand,
    iconYandex_brand,
    iconYandexInternational_brand,
    iconYelp_brand,
    iconYoast_brand,
    iconYoutube_brand,
    iconYoutubeSquare_brand,
}
export { IconDefinition } from '@fortawesome/fontawesome-svg-core';
